import { ROUTES } from '@constants/routes';

/** Paths with real page implementations (not Coming Soon placeholders). */
export const IMPLEMENTED_PATHS = new Set<string>([
  ROUTES.dashboard,
  ROUTES.academics.sessions,
  ROUTES.academics.classes,
  ROUTES.academics.sections,
  ROUTES.academics.classSections,
  ROUTES.academics.subjects,
  ROUTES.academics.subjectGroups,
  ROUTES.academics.timetable,
  ROUTES.academics.teacherTimetable,
  ROUTES.academics.classTeacher,
  ROUTES.academics.promote,
  ROUTES.students.root,
  ROUTES.students.disabled,
  ROUTES.students.onlineAdmission,
  ROUTES.frontOffice.enquiry,
  ROUTES.staff.root,
  ROUTES.staff.leave,
  ROUTES.staff.leaveTypes,
  ROUTES.staff.leaveAllotments,
  ROUTES.fees.feeTypes,
  ROUTES.fees.feeGroups,
  ROUTES.fees.discounts,
  ROUTES.fees.discountsAssign,
  ROUTES.fees.assign,
  ROUTES.fees.collect,
  ROUTES.fees.dueSearch,
  ROUTES.fees.paymentSearch,
  ROUTES.fees.reminders,
  ROUTES.fees.paymentGateways,
  ROUTES.fees.offlinePayments,
  ROUTES.attendance.mark,
  ROUTES.attendance.report,
  ROUTES.attendance.approveLeave,
  ROUTES.examinations.groups,
  ROUTES.examinations.exams,
  ROUTES.examinations.enroll,
  ROUTES.examinations.schedule,
  ROUTES.examinations.results,
  ROUTES.examinations.grades,
  ROUTES.examinations.divisions,
  ROUTES.examinations.cbseExams,
  ROUTES.transport.fees,
  ROUTES.transport.pickupPoints,
  ROUTES.transport.routes,
  ROUTES.transport.vehicles,
  ROUTES.transport.assignVehicle,
  ROUTES.hostel.rooms,
  ROUTES.hostel.roomTypes,
  ROUTES.hostel.hostels,
  ROUTES.communicate.notices,
  ROUTES.settings.general,
  ROUTES.settings.languages,
  ROUTES.settings.currency,
  ROUTES.lessonPlan.syllabusStatus,
  ROUTES.lessonPlan.lessons,
]);

export function isImplementedPath(path: string): boolean {
  return IMPLEMENTED_PATHS.has(path);
}
