from django.db import models


class Students(models.Model):
    """Maps to `students` in db_current."""

    id = models.AutoField(primary_key=True)
    parent_id = models.IntegerField()
    admission_no = models.CharField(max_length=100, blank=True, null=True)
    roll_no = models.BigIntegerField(blank=True, null=True)
    admission_date = models.DateField(blank=True, null=True)
    firstname = models.CharField(max_length=100, blank=True, null=True)
    middlename = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=100, blank=True, null=True)
    rte = models.CharField(max_length=20, blank=True, null=True)
    image = models.CharField(max_length=500, blank=True, null=True)
    mobileno = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    pincode = models.CharField(max_length=100, blank=True, null=True)
    religion = models.CharField(max_length=100, blank=True, null=True)
    cast = models.CharField(max_length=50, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True, null=True)
    current_address = models.TextField(blank=True, null=True)
    permanent_address = models.TextField(blank=True, null=True)
    category_id = models.CharField(max_length=100, blank=True, null=True)
    school_house_id = models.IntegerField(blank=True, null=True)
    blood_group = models.CharField(max_length=200)
    hostel_room_id = models.IntegerField(blank=True, null=True)
    room_bed_id = models.IntegerField(blank=True, null=True)
    adhar_no = models.CharField(max_length=100, blank=True, null=True)
    samagra_id = models.CharField(max_length=100, blank=True, null=True)
    bank_account_no = models.CharField(max_length=100, blank=True, null=True)
    bank_name = models.CharField(max_length=100, blank=True, null=True)
    ifsc_code = models.CharField(max_length=100, blank=True, null=True)
    guardian_is = models.CharField(max_length=100)
    father_name = models.CharField(max_length=100, blank=True, null=True)
    father_phone = models.CharField(max_length=100, blank=True, null=True)
    father_occupation = models.CharField(max_length=100, blank=True, null=True)
    mother_name = models.CharField(max_length=100, blank=True, null=True)
    mother_phone = models.CharField(max_length=100, blank=True, null=True)
    mother_occupation = models.CharField(max_length=100, blank=True, null=True)
    guardian_name = models.CharField(max_length=100, blank=True, null=True)
    guardian_relation = models.CharField(max_length=100, blank=True, null=True)
    guardian_phone = models.CharField(max_length=100, blank=True, null=True)
    guardian_occupation = models.CharField(max_length=150)
    guardian_address = models.TextField(blank=True, null=True)
    guardian_email = models.CharField(max_length=100, blank=True, null=True)
    father_pic = models.CharField(max_length=200)
    mother_pic = models.CharField(max_length=200)
    guardian_pic = models.CharField(max_length=200)
    father_aadhar = models.CharField(max_length=50, blank=True, null=True)
    mother_aadhar = models.CharField(max_length=50, blank=True, null=True)
    is_active = models.CharField(max_length=255, blank=True, null=True, default="yes")
    previous_school = models.TextField(blank=True, null=True)
    height = models.CharField(max_length=100)
    weight = models.CharField(max_length=100)
    measurement_date = models.DateField(blank=True, null=True)
    dis_reason = models.IntegerField()
    note = models.CharField(max_length=200, blank=True, null=True)
    dis_note = models.TextField()
    app_key = models.TextField(blank=True, null=True)
    parent_app_key = models.TextField(blank=True, null=True)
    disable_at = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateField(blank=True, null=True)
    face_auth = models.IntegerField(default=0)

    class Meta:
        managed = False
        db_table = "students"

    def __str__(self):
        return f"Students {self.pk}"
