# Generated by Django 5.1.15 on 2026-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConferenceStaff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("conference_id", models.IntegerField(db_index=True)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "conference_staff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CycStaffPayroll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "employee_id",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                ("payroll_type", models.CharField(max_length=44)),
                ("payroll_title", models.CharField(max_length=255)),
                ("payroll_amount", models.FloatField()),
            ],
            options={
                "db_table": "cyc_staff_payroll",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CycStaffPayrollIncrement",
            fields=[
                ("pi_id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.IntegerField()),
                ("month", models.CharField(blank=True, max_length=44, null=True)),
                ("year", models.CharField(blank=True, max_length=44, null=True)),
                ("basic_salary", models.FloatField()),
                ("increment", models.FloatField()),
                ("date", models.DateField()),
                ("entry_by", models.IntegerField()),
                ("status", models.CharField(default="pending", max_length=44)),
                ("action_by", models.IntegerField()),
                ("action_date", models.DateField()),
            ],
            options={
                "db_table": "cyc_staff_payroll_increment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="yes", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GmeetStaff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gmeet_id", models.IntegerField(db_index=True)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "gmeet_staff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveTypes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(db_index=True, max_length=200)),
                ("is_active", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "leave_types",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PayslipAllowance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payslip_id", models.IntegerField(db_index=True)),
                ("allowance_type", models.CharField(max_length=200)),
                ("amount", models.TextField()),
                ("staff_id", models.IntegerField(db_index=True)),
                ("cal_type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "payslip_allowance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("lang_id", models.IntegerField(blank=True, default=1, null=True)),
                ("currency_id", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "department",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "designation",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("work_exp", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("surname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("contact_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "emergency_contact_no",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("date_of_leaving", models.DateField(blank=True, null=True)),
                (
                    "local_address",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "permanent_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(blank=True, max_length=250, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "account_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                ("ifsc_code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payscale", models.CharField(blank=True, max_length=200, null=True)),
                ("basic_salary", models.IntegerField(blank=True, null=True)),
                ("epf_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shift", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("facebook", models.CharField(blank=True, max_length=200, null=True)),
                ("twitter", models.CharField(blank=True, max_length=200, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=200, null=True)),
                ("instagram", models.CharField(blank=True, max_length=200, null=True)),
                ("resume", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "joining_letter",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "resignation_letter",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "other_document_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "other_document_file",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, default=1, null=True)),
                ("direct_manager", models.IntegerField(blank=True, null=True)),
                ("is_house_incharge", models.IntegerField(default=0)),
                ("verification_code", models.CharField(max_length=100)),
                (
                    "zoom_api_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "zoom_api_secret",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "biometric_device_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("disable_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "staff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                ("staff_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "staff_attendance_type_id",
                    models.IntegerField(
                        blank=True, db_index=True, default=1, null=True
                    ),
                ),
                (
                    "biometric_attendence",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("biometric_device_data", models.TextField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.IntegerField(blank=True, default=1, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "staff_attendance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffAttendanceType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=200, null=True)),
                ("key_value", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="yes", max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "staff_attendance_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffDesignation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="yes", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "staff_designation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffIdCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("school_name", models.CharField(max_length=255)),
                ("school_address", models.CharField(max_length=255)),
                ("background", models.CharField(max_length=100)),
                ("logo", models.CharField(max_length=100)),
                ("sign_image", models.CharField(max_length=100)),
                ("header_color", models.CharField(max_length=100)),
                ("enable_vertical_card", models.IntegerField(default=0)),
                ("enable_staff_role", models.IntegerField()),
                ("enable_staff_id", models.IntegerField()),
                ("enable_staff_department", models.IntegerField()),
                ("enable_designation", models.IntegerField()),
                ("enable_name", models.IntegerField()),
                ("enable_fathers_name", models.IntegerField()),
                ("enable_mothers_name", models.IntegerField()),
                ("enable_date_of_joining", models.IntegerField()),
                ("enable_permanent_address", models.IntegerField()),
                ("enable_staff_dob", models.IntegerField()),
                ("enable_staff_phone", models.IntegerField()),
                ("enable_staff_barcode", models.IntegerField()),
                ("status", models.IntegerField()),
            ],
            options={
                "db_table": "staff_id_card",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffLeaveDetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("leave_type_id", models.IntegerField(db_index=True)),
                ("alloted_leave", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "staff_leave_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffLeaveRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("leave_type_id", models.IntegerField(db_index=True)),
                ("leave_from", models.DateField()),
                ("leave_to", models.DateField()),
                ("leave_days", models.IntegerField()),
                ("employee_remark", models.CharField(max_length=200)),
                ("admin_remark", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=50)),
                (
                    "applied_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("document_file", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "staff_leave_request",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffPayroll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("basic_salary", models.IntegerField()),
                ("pay_scale", models.CharField(max_length=200)),
                ("grade", models.CharField(max_length=50)),
                ("is_active", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "staff_payroll",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffPayslip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("basic", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "total_allowance",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "total_deduction",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "leave_deduction",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "tax",
                    models.CharField(
                        blank=True, default="0", max_length=200, null=True
                    ),
                ),
                ("net_salary", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="unpaid", max_length=100, null=True
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=200, null=True)),
                ("year", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("linked_ledger_bank", models.IntegerField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=44, null=True),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
                ("generated_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_modes",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "staff_payslip",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffRating",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("comment", models.TextField()),
                ("rate", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("role", models.CharField(max_length=255)),
                ("status", models.IntegerField()),
                ("entrydt", models.DateTimeField()),
            ],
            options={
                "db_table": "staff_rating",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StaffTimeline",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("staff_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("timeline_date", models.DateField()),
                ("description", models.CharField(max_length=300)),
                ("document", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "staff_timeline",
                "managed": False,
            },
        ),
    ]
