from django.db import models


class OnlineAdmissions(models.Model):
    """Maps to `online_admissions` in db_current."""

    id = models.AutoField(primary_key=True)
    admission_no = models.CharField(max_length=100, blank=True, null=True)
    roll_no = models.CharField(max_length=100, blank=True, null=True)
    reference_no = models.CharField(max_length=50)
    admission_date = models.DateField(blank=True, null=True)
    firstname = models.CharField(max_length=100, blank=True, null=True)
    middlename = models.CharField(max_length=255)
    lastname = models.CharField(max_length=100, blank=True, null=True)
    rte = models.CharField(max_length=20, default="No")
    image = models.CharField(max_length=255, blank=True, null=True)
    mobileno = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    pincode = models.CharField(max_length=100, blank=True, null=True)
    religion = models.CharField(max_length=100, blank=True, null=True)
    cast = models.CharField(max_length=50)
    dob = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True, null=True)
    current_address = models.TextField(blank=True, null=True)
    permanent_address = models.TextField(blank=True, null=True)
    category_id = models.IntegerField(blank=True, null=True, db_index=True)
    class_section_id = models.IntegerField(blank=True, null=True, db_index=True)
    route_id = models.IntegerField()
    school_house_id = models.IntegerField(blank=True, null=True, db_index=True)
    blood_group = models.CharField(max_length=200)
    vehroute_id = models.IntegerField()
    hostel_room_id = models.IntegerField(blank=True, null=True, db_index=True)
    adhar_no = models.CharField(max_length=100, blank=True, null=True)
    samagra_id = models.CharField(max_length=100, blank=True, null=True)
    bank_account_no = models.CharField(max_length=100, blank=True, null=True)
    bank_name = models.CharField(max_length=100, blank=True, null=True)
    ifsc_code = models.CharField(max_length=100, blank=True, null=True)
    guardian_is = models.CharField(max_length=100)
    father_name = models.CharField(max_length=100, blank=True, null=True)
    father_phone = models.CharField(max_length=100, blank=True, null=True)
    father_occupation = models.CharField(max_length=100, blank=True, null=True)
    mother_name = models.CharField(max_length=100, blank=True, null=True)
    mother_phone = models.CharField(max_length=100, blank=True, null=True)
    mother_occupation = models.CharField(max_length=100, blank=True, null=True)
    guardian_name = models.CharField(max_length=100, blank=True, null=True)
    guardian_relation = models.CharField(max_length=100, blank=True, null=True)
    guardian_phone = models.CharField(max_length=100, blank=True, null=True)
    guardian_occupation = models.CharField(max_length=150)
    guardian_address = models.TextField(blank=True, null=True)
    guardian_email = models.CharField(max_length=100)
    father_pic = models.CharField(max_length=255)
    mother_pic = models.CharField(max_length=255)
    guardian_pic = models.CharField(max_length=255)
    is_enroll = models.IntegerField(blank=True, null=True, default=0)
    previous_school = models.TextField(blank=True, null=True)
    height = models.CharField(max_length=100)
    weight = models.CharField(max_length=100)
    note = models.TextField()
    form_status = models.IntegerField()
    paid_status = models.IntegerField()
    measurement_date = models.DateField(blank=True, null=True)
    app_key = models.TextField(blank=True, null=True)
    document = models.TextField(blank=True, null=True)
    submit_date = models.DateField(blank=True, null=True)
    disable_at = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "online_admissions"

    def __str__(self):
        return f"OnlineAdmissions {self.pk}"
