/** Application roles — mapped from auth user.role / is_superadmin. */
export type AppRole = 'superadmin' | 'admin' | 'teacher' | 'accountant' | 'guest';

/** Fine-grained permissions for UI gating (backend enforcement is separate). */
export type Permission =
  | 'students.view'
  | 'students.create'
  | 'students.delete'
  | 'staff.view'
  | 'staff.create'
  | 'staff.edit'
  | 'staff.delete'
  | 'settings.manage'
  | 'general_settings.view'
  | 'general_settings.edit'
  | 'academics.manage'
  | 'classes.view'
  | 'classes.create'
  | 'classes.edit'
  | 'classes.delete'
  | 'sections.view'
  | 'sections.create'
  | 'sections.edit'
  | 'sections.delete'
  | 'subjects.view'
  | 'subjects.create'
  | 'subjects.edit'
  | 'subjects.delete'
  | 'subject_groups.view'
  | 'subject_groups.create'
  | 'subject_groups.edit'
  | 'subject_groups.delete'
  | 'timetable.view'
  | 'timetable.create'
  | 'timetable.edit'
  | 'timetable.delete'
  | 'class_teacher.view'
  | 'class_teacher.create'
  | 'class_teacher.edit'
  | 'class_teacher.delete'
  | 'sessions.view'
  | 'sessions.create'
  | 'sessions.edit'
  | 'sessions.delete'
  | 'exams.view'
  | 'exams.create'
  | 'exams.edit'
  | 'exams.delete'
  | 'exams.submit'
  | 'exams.approve'
  | 'fees.manage'
  | 'attendance.mark'
  | 'attendance.report'
  | 'notifications.view';
