export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    logout: '/auth/logout/',
    me: '/auth/me/',
    tokenRefresh: '/auth/token/refresh/',
  },
  settings: {
    sessions: '/academics/sessions/',
    sessionDetail: (id: number) => `/academics/sessions/${id}/`,
    sessionActivate: (id: number) => `/academics/sessions/${id}/activate/`,
    general: '/settings/general/',
    languages: '/settings/languages/',
    languageDetail: (id: number) => `/settings/languages/${id}/`,
    currencies: '/settings/currencies/',
    currencyDetail: (id: number) => `/settings/currencies/${id}/`,
    currencyActivate: (id: number) => `/settings/currencies/${id}/activate/`,
  },
  academics: {
    classes: '/academics/classes/',
    classDetail: (id: number) => `/academics/classes/${id}/`,
    sections: '/academics/sections/',
    sectionDetail: (id: number) => `/academics/sections/${id}/`,
    classSections: '/academics/class-sections/',
    classSectionDetail: (id: number) => `/academics/class-sections/${id}/`,
    subjects: '/academics/subjects/',
    subjectDetail: (id: number) => `/academics/subjects/${id}/`,
  },
  students: {
    list: '/students/',
    detail: (id: number) => `/students/${id}/`,
    fees: (id: number) => `/students/${id}/fees/`,
  },
  staff: {
    list: '/staff/',
    detail: (id: number) => `/staff/${id}/`,
    departments: '/staff/departments/',
    designations: '/staff/designations/',
    documentUpload: (id: number) => `/staff/${id}/documents/upload/`,
    documentDelete: (id: number) => `/staff/${id}/documents/delete/`,
  },
  fees: {
    categories: '/fees/categories/',
    categoryDetail: (id: number) => `/fees/categories/${id}/`,
    feeTypes: '/fees/fee-types/',
    feeTypeDetail: (id: number) => `/fees/fee-types/${id}/`,
    feeGroups: '/fees/fee-groups/',
    feeGroupDetail: (id: number) => `/fees/fee-groups/${id}/`,
    assignments: '/fees/assignments/',
    assignmentDetail: (id: number) => `/fees/assignments/${id}/`,
  },
  attendance: {
    types: '/attendance/types/',
    roster: '/attendance/roster/',
    mark: '/attendance/mark/',
    report: '/attendance/report/',
    approveLeave: '/attendance/approve-leave/',
    approveLeaveDetail: (id: string) => `/attendance/approve-leave/${id}/`,
  },
  examinations: {
    groups: '/examinations/groups/',
    groupDetail: (id: number) => `/examinations/groups/${id}/`,
    exams: '/examinations/exams/',
    examDetail: (id: number) => `/examinations/exams/${id}/`,
    schedules: '/examinations/schedules/',
    scheduleDetail: (id: number) => `/examinations/schedules/${id}/`,
  },
  health: '/health/',
} as const;
