export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    logout: '/auth/logout/',
    me: '/auth/me/',
    tokenRefresh: '/auth/token/refresh/',
  },
  settings: {
    sessions: '/academics/sessions/',
    sessionActive: '/academics/sessions/active/',
    sessionDetail: (id: number) => `/academics/sessions/${id}/`,
    sessionActivate: (id: number) => `/academics/sessions/${id}/activate/`,
    general: '/settings/general/',
    languages: '/settings/languages/',
    languageDetail: (id: number) => `/settings/languages/${id}/`,
    currencies: '/settings/currencies/',
    currencyDetail: (id: number) => `/settings/currencies/${id}/`,
    currencyActivate: (id: number) => `/settings/currencies/${id}/activate/`,
  },
  academics: {
    classes: '/academics/classes/',
    classDetail: (id: number) => `/academics/classes/${id}/`,
    sections: '/academics/sections/',
    sectionDetail: (id: number) => `/academics/sections/${id}/`,
    classSections: '/academics/class-sections/',
    classSectionDetail: (id: number) => `/academics/class-sections/${id}/`,
    subjects: '/academics/subjects/',
    subjectDetail: (id: number) => `/academics/subjects/${id}/`,
    subjectGroups: '/academics/subject-groups/',
    subjectGroupDetail: (id: number) => `/academics/subject-groups/${id}/`,
    subjectGroupSubjects: (id: number) => `/academics/subject-groups/${id}/subjects/`,
    subjectGroupClassSections: (id: number) => `/academics/subject-groups/${id}/class-sections/`,
    timetable: '/academics/timetable/',
    timetableTeacher: '/academics/timetable/teacher/',
    timetableSubjectOptions: '/academics/timetable/subject-options/',
    timetableDetail: (id: number) => `/academics/timetable/${id}/`,
    classTeachers: '/academics/class-teachers/',
    classTeacherDetail: (id: number) => `/academics/class-teachers/${id}/`,
    promotePreview: '/academics/promote/preview/',
    promote: '/academics/promote/',
  },
  students: {
    list: '/students/',
    detail: (id: number) => `/students/${id}/`,
    fees: (id: number) => `/students/${id}/fees/`,
    disableReasons: '/students/disable-reasons/',
    enable: (id: number) => `/students/${id}/enable/`,
  },
  staff: {
    list: '/staff/',
    detail: (id: number) => `/staff/${id}/`,
    departments: '/staff/departments/',
    designations: '/staff/designations/',
    leaveTypes: '/staff/leave-types/',
    leaveTypeDetail: (id: number) => `/staff/leave-types/${id}/`,
    leaveRequests: '/staff/leave-requests/',
    leaveRequestDetail: (id: number) => `/staff/leave-requests/${id}/`,
    leaveAllotments: '/staff/leave-allotments/',
    leaveAllotmentsRoster: '/staff/leave-allotments/roster/',
    leaveAllotmentDetail: (id: number) => `/staff/leave-allotments/${id}/`,
    documentUpload: (id: number) => `/staff/${id}/documents/upload/`,
    documentDelete: (id: number) => `/staff/${id}/documents/delete/`,
  },
  fees: {
    categories: '/fees/categories/',
    categoryDetail: (id: number) => `/fees/categories/${id}/`,
    feeTypes: '/fees/fee-types/',
    feeTypeDetail: (id: number) => `/fees/fee-types/${id}/`,
    feeGroups: '/fees/fee-groups/',
    feeGroupDetail: (id: number) => `/fees/fee-groups/${id}/`,
    discounts: '/fees/discounts/',
    discountDetail: (id: number) => `/fees/discounts/${id}/`,
    discountAssignRoster: '/fees/discount-assignments/roster/',
    discountAssignments: '/fees/discount-assignments/',
    discountAssignmentDetail: (id: number) => `/fees/discount-assignments/${id}/`,
    assignments: '/fees/assignments/',
    assignmentDetail: (id: number) => `/fees/assignments/${id}/`,
    collectRoster: '/fees/collect/roster/',
    searchDue: '/fees/search/due/',
    searchPayments: '/fees/search/payments/',
    reminders: '/fees/reminders/',
    reminderDetail: (id: number) => `/fees/reminders/${id}/`,
  },
  attendance: {
    types: '/attendance/types/',
    roster: '/attendance/roster/',
    mark: '/attendance/mark/',
    report: '/attendance/report/',
    approveLeave: '/attendance/approve-leave/',
    approveLeaveDetail: (id: string) => `/attendance/approve-leave/${id}/`,
  },
  examinations: {
    groups: '/examinations/groups/',
    groupDetail: (id: number) => `/examinations/groups/${id}/`,
    exams: '/examinations/exams/',
    examDetail: (id: number) => `/examinations/exams/${id}/`,
    schedules: '/examinations/schedules/',
    scheduleDetail: (id: number) => `/examinations/schedules/${id}/`,
    grades: '/examinations/grades/',
    gradeDetail: (id: number) => `/examinations/grades/${id}/`,
    divisions: '/examinations/divisions/',
    divisionDetail: (id: number) => `/examinations/divisions/${id}/`,
    resultsRoster: '/examinations/results/roster/',
    results: '/examinations/results/',
    enrollmentsRoster: '/examinations/enrollments/roster/',
    enrollments: '/examinations/enrollments/',
    enrollmentDetail: (id: number) => `/examinations/enrollments/${id}/`,
  },
  transport: {
    fees: '/transport/fees/',
    feeDetail: (id: number) => `/transport/fees/${id}/`,
    pickupPoints: '/transport/pickup-points/',
    pickupPointDetail: (id: number) => `/transport/pickup-points/${id}/`,
    routes: '/transport/routes/',
    routeDetail: (id: number) => `/transport/routes/${id}/`,
    vehicles: '/transport/vehicles/',
    vehicleDetail: (id: number) => `/transport/vehicles/${id}/`,
    assignVehicles: '/transport/assign-vehicles/',
    assignVehicleDetail: (id: number) => `/transport/assign-vehicles/${id}/`,
  },
  health: '/health/',
} as const;
