export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    logout: '/auth/logout/',
    me: '/auth/me/',
    tokenRefresh: '/auth/token/refresh/',
  },
  settings: {
    sessions: '/academics/sessions/',
    sessionActive: '/academics/sessions/active/',
    sessionDetail: (id: number) => `/academics/sessions/${id}/`,
    sessionActivate: (id: number) => `/academics/sessions/${id}/activate/`,
    general: '/settings/general/',
    languages: '/settings/languages/',
    languageDetail: (id: number) => `/settings/languages/${id}/`,
    currencies: '/settings/currencies/',
    currencyDetail: (id: number) => `/settings/currencies/${id}/`,
    currencyActivate: (id: number) => `/settings/currencies/${id}/activate/`,
    roles: '/settings/roles/',
    roleDetail: (id: number) => `/settings/roles/${id}/`,
    rolePermissions: (id: number) => `/settings/roles/${id}/permissions/`,
    users: '/settings/users/',
    userDetail: (id: number) => `/settings/users/${id}/`,
    userRoleOptions: '/settings/users/role-options/',
  },
  academics: {
    classes: '/academics/classes/',
    classDetail: (id: number) => `/academics/classes/${id}/`,
    sections: '/academics/sections/',
    sectionDetail: (id: number) => `/academics/sections/${id}/`,
    classSections: '/academics/class-sections/',
    classSectionDetail: (id: number) => `/academics/class-sections/${id}/`,
    subjects: '/academics/subjects/',
    subjectDetail: (id: number) => `/academics/subjects/${id}/`,
    subjectGroups: '/academics/subject-groups/',
    subjectGroupDetail: (id: number) => `/academics/subject-groups/${id}/`,
    subjectGroupSubjects: (id: number) => `/academics/subject-groups/${id}/subjects/`,
    subjectGroupClassSections: (id: number) => `/academics/subject-groups/${id}/class-sections/`,
    timetable: '/academics/timetable/',
    timetableTeacher: '/academics/timetable/teacher/',
    timetableSubjectOptions: '/academics/timetable/subject-options/',
    timetableDetail: (id: number) => `/academics/timetable/${id}/`,
    classTeachers: '/academics/class-teachers/',
    classTeacherDetail: (id: number) => `/academics/class-teachers/${id}/`,
    promotePreview: '/academics/promote/preview/',
    promote: '/academics/promote/',
    homework: '/academics/homework/',
    homeworkDetail: (id: number) => `/academics/homework/${id}/`,
    dailyAssignments: '/academics/daily-assignments/',
    dailyAssignmentDetail: (id: number) => `/academics/daily-assignments/${id}/`,
  },
  students: {
    list: '/students/',
    detail: (id: number) => `/students/${id}/`,
    fees: (id: number) => `/students/${id}/fees/`,
    transport: (id: number) => `/students/${id}/transport/`,
    disableReasons: '/students/disable-reasons/',
    enable: (id: number) => `/students/${id}/enable/`,
    categories: '/students/categories/',
    categoryDetail: (id: number) => `/students/categories/${id}/`,
    houses: '/students/houses/',
    houseDetail: (id: number) => `/students/houses/${id}/`,
    import: '/students/import/',
    importTemplate: '/students/import/template/',
  },
  staff: {
    list: '/staff/',
    detail: (id: number) => `/staff/${id}/`,
    departments: '/staff/departments/',
    departmentDetail: (id: number) => `/staff/departments/${id}/`,
    designations: '/staff/designations/',
    designationDetail: (id: number) => `/staff/designations/${id}/`,
    attendanceTypes: '/staff/attendance/types/',
    attendanceRoster: '/staff/attendance/roster/',
    attendanceMark: '/staff/attendance/mark/',
    payrollScales: '/staff/payroll/scales/',
    payrollScaleDetail: (id: number) => `/staff/payroll/scales/${id}/`,
    payrollPayslips: '/staff/payroll/payslips/',
    payrollPayslipDetail: (id: number) => `/staff/payroll/payslips/${id}/`,
    leaveTypes: '/staff/leave-types/',
    leaveTypeDetail: (id: number) => `/staff/leave-types/${id}/`,
    leaveRequests: '/staff/leave-requests/',
    leaveRequestDetail: (id: number) => `/staff/leave-requests/${id}/`,
    leaveAllotments: '/staff/leave-allotments/',
    leaveAllotmentsRoster: '/staff/leave-allotments/roster/',
    leaveAllotmentDetail: (id: number) => `/staff/leave-allotments/${id}/`,
    documentUpload: (id: number) => `/staff/${id}/documents/upload/`,
    documentDelete: (id: number) => `/staff/${id}/documents/delete/`,
  },
  fees: {
    categories: '/fees/categories/',
    categoryDetail: (id: number) => `/fees/categories/${id}/`,
    feeTypes: '/fees/fee-types/',
    feeTypeDetail: (id: number) => `/fees/fee-types/${id}/`,
    feeGroups: '/fees/fee-groups/',
    feeGroupDetail: (id: number) => `/fees/fee-groups/${id}/`,
    discounts: '/fees/discounts/',
    discountDetail: (id: number) => `/fees/discounts/${id}/`,
    discountAssignRoster: '/fees/discount-assignments/roster/',
    discountAssignments: '/fees/discount-assignments/',
    discountAssignmentDetail: (id: number) => `/fees/discount-assignments/${id}/`,
    assignments: '/fees/assignments/',
    assignmentDetail: (id: number) => `/fees/assignments/${id}/`,
    collectRoster: '/fees/collect/roster/',
    searchDue: '/fees/search/due/',
    searchPayments: '/fees/search/payments/',
    reminders: '/fees/reminders/',
    reminderDetail: (id: number) => `/fees/reminders/${id}/`,
    paymentGateways: '/fees/payment-gateways/',
    offlinePayments: '/fees/offline-payments/',
    offlinePaymentDetail: (id: number) => `/fees/offline-payments/${id}/`,
    offlinePaymentApprove: (id: number) => `/fees/offline-payments/${id}/approve/`,
    offlinePaymentReject: (id: number) => `/fees/offline-payments/${id}/reject/`,
  },
  attendance: {
    types: '/attendance/types/',
    roster: '/attendance/roster/',
    mark: '/attendance/mark/',
    report: '/attendance/report/',
    approveLeave: '/attendance/approve-leave/',
    approveLeaveDetail: (id: string) => `/attendance/approve-leave/${id}/`,
  },
  examinations: {
    groups: '/examinations/groups/',
    groupDetail: (id: number) => `/examinations/groups/${id}/`,
    exams: '/examinations/exams/',
    examDetail: (id: number) => `/examinations/exams/${id}/`,
    schedules: '/examinations/schedules/',
    scheduleDetail: (id: number) => `/examinations/schedules/${id}/`,
    grades: '/examinations/grades/',
    gradeDetail: (id: number) => `/examinations/grades/${id}/`,
    divisions: '/examinations/divisions/',
    divisionDetail: (id: number) => `/examinations/divisions/${id}/`,
    resultsRoster: '/examinations/results/roster/',
    results: '/examinations/results/',
    enrollmentsRoster: '/examinations/enrollments/roster/',
    enrollments: '/examinations/enrollments/',
    enrollmentDetail: (id: number) => `/examinations/enrollments/${id}/`,
    cbseExams: '/examinations/cbse-exams/',
  },
  hostel: {
    hostels: '/hostel/hostels/',
    hostelDetail: (id: number) => `/hostel/hostels/${id}/`,
    rooms: '/hostel/rooms/',
    roomDetail: (id: number) => `/hostel/rooms/${id}/`,
    roomTypes: '/hostel/room-types/',
    roomTypeDetail: (id: number) => `/hostel/room-types/${id}/`,
  },
  communications: {
    notices: '/communications/notices/',
    noticeDetail: (id: number) => `/communications/notices/${id}/`,
  },
  transport: {
    fees: '/transport/fees/',
    feeDetail: (id: number) => `/transport/fees/${id}/`,
    pickupPoints: '/transport/pickup-points/',
    pickupPointDetail: (id: number) => `/transport/pickup-points/${id}/`,
    routes: '/transport/routes/',
    routeDetail: (id: number) => `/transport/routes/${id}/`,
    vehicles: '/transport/vehicles/',
    vehicleDetail: (id: number) => `/transport/vehicles/${id}/`,
    assignVehicles: '/transport/assign-vehicles/',
    assignVehicleDetail: (id: number) => `/transport/assign-vehicles/${id}/`,
    routePickupPoints: '/transport/route-pickup-points/',
    routePickupPointDetail: (id: number) => `/transport/route-pickup-points/${id}/`,
  },
  frontOffice: {
    enquiries: '/front-office/enquiries/',
    enquiryDetail: (id: number) => `/front-office/enquiries/${id}/`,
    visitors: '/front-office/visitors/',
    visitorDetail: (id: number) => `/front-office/visitors/${id}/`,
    complaints: '/front-office/complaints/',
    complaintDetail: (id: number) => `/front-office/complaints/${id}/`,
    postal: '/front-office/postal/',
    postalDetail: (id: number) => `/front-office/postal/${id}/`,
  },
  admissions: {
    online: '/admissions/online/',
    onlineDetail: (id: number) => `/admissions/online/${id}/`,
    convert: (id: number) => `/admissions/online/${id}/convert/`,
  },
  library: {
    books: '/library/books/',
    bookDetail: (id: number) => `/library/books/${id}/`,
    issues: '/library/issues/',
    issueReturn: (id: number) => `/library/issues/${id}/return/`,
    members: '/library/members/',
  },
  inventory: {
    categories: '/inventory/categories/',
    categoryDetail: (id: number) => `/inventory/categories/${id}/`,
    stores: '/inventory/stores/',
    storeDetail: (id: number) => `/inventory/stores/${id}/`,
    suppliers: '/inventory/suppliers/',
    supplierDetail: (id: number) => `/inventory/suppliers/${id}/`,
    items: '/inventory/items/',
    itemDetail: (id: number) => `/inventory/items/${id}/`,
    stock: '/inventory/stock/',
    stockDetail: (id: number) => `/inventory/stock/${id}/`,
    issues: '/inventory/issues/',
    issueReturn: (id: number) => `/inventory/issues/${id}/return/`,
  },
  income: {
    list: '/income/',
    detail: (id: number) => `/income/${id}/`,
    heads: '/income/heads/',
    headDetail: (id: number) => `/income/heads/${id}/`,
  },
  expense: {
    list: '/expense/',
    detail: (id: number) => `/expense/${id}/`,
    heads: '/expense/heads/',
    headDetail: (id: number) => `/expense/heads/${id}/`,
  },
  documents: {
    certificates: '/documents/certificates/',
    certificateDetail: (id: number) => `/documents/certificates/${id}/`,
    certificateGenerate: '/documents/certificates/generate/',
    studentIdCards: '/documents/id-cards/student/',
    studentIdCardDetail: (id: number) => `/documents/id-cards/student/${id}/`,
    studentIdCardGenerate: '/documents/id-cards/student/generate/',
    staffIdCards: '/documents/id-cards/staff/',
    staffIdCardDetail: (id: number) => `/documents/id-cards/staff/${id}/`,
    staffIdCardGenerate: '/documents/id-cards/staff/generate/',
    contentTypes: '/documents/download-center/content-types/',
    contentTypeDetail: (id: number) => `/documents/download-center/content-types/${id}/`,
    uploadContent: '/documents/download-center/content/',
    uploadContentDetail: (id: number) => `/documents/download-center/content/${id}/`,
  },
  finance: {
    groups: '/finance/groups/',
    groupDetail: (id: number) => `/finance/groups/${id}/`,
    ledgers: '/finance/ledgers/',
    ledgerDetail: (id: number) => `/finance/ledgers/${id}/`,
    entryTypes: '/finance/entry-types/',
    entries: '/finance/entries/',
    entryDetail: (id: number) => `/finance/entries/${id}/`,
    mapper: '/finance/mapper/',
    mapperDetail: (id: number) => `/finance/mapper/${id}/`,
    trialBalance: '/finance/reports/trial-balance/',
  },
  health: '/health/',
} as const;
