import type { AppRole, Permission } from '@app-types/permissions';

const ALL_PERMISSIONS: Permission[] = [
  'students.view',
  'students.create',
  'students.delete',
  'staff.view',
  'staff.create',
  'staff.edit',
  'staff.delete',
  'settings.manage',
  'general_settings.view',
  'general_settings.edit',
  'academics.manage',
  'classes.view',
  'classes.create',
  'classes.edit',
  'classes.delete',
  'sections.view',
  'sections.create',
  'sections.edit',
  'sections.delete',
  'subjects.view',
  'subjects.create',
  'subjects.edit',
  'subjects.delete',
  'subject_groups.view',
  'subject_groups.create',
  'subject_groups.edit',
  'subject_groups.delete',
  'timetable.view',
  'timetable.create',
  'timetable.edit',
  'timetable.delete',
  'teacher_timetable.view',
  'class_teacher.view',
  'class_teacher.create',
  'class_teacher.edit',
  'class_teacher.delete',
  'promote_students.view',
  'promote_students.create',
  'sessions.view',
  'sessions.create',
  'sessions.edit',
  'sessions.delete',
  'exams.view',
  'exams.create',
  'exams.edit',
  'exams.delete',
  'exams.submit',
  'exams.approve',
  'fees.manage',
  'attendance.mark',
  'attendance.report',
  'notifications.view',
];

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  superadmin: ALL_PERMISSIONS,
  admin: ALL_PERMISSIONS,
  teacher: [
    'students.view',
    'staff.view',
    'exams.view',
    'exams.create',
    'exams.edit',
    'exams.submit',
    'attendance.mark',
    'attendance.report',
    'notifications.view',
  ],
  accountant: [
    'students.view',
    'staff.view',
    'fees.manage',
    'attendance.report',
    'notifications.view',
  ],
  guest: [],
};

export const PERMISSION_DENIED_MESSAGES: Partial<Record<Permission, string>> = {
  'students.delete': 'You do not have permission to delete students.',
  'students.create': 'You do not have permission to admit students.',
  'staff.create': 'You do not have permission to add staff.',
  'staff.edit': 'You do not have permission to edit staff.',
  'staff.delete': 'You do not have permission to delete staff.',
  'settings.manage': 'Only administrators can change school settings.',
  'general_settings.edit': 'You do not have permission to edit general settings.',
  'academics.manage': 'You do not have permission to manage academic structure.',
  'classes.create': 'You do not have permission to create classes.',
  'classes.edit': 'You do not have permission to edit classes.',
  'classes.delete': 'You do not have permission to deactivate classes.',
  'sections.create': 'You do not have permission to create sections.',
  'sections.edit': 'You do not have permission to edit sections.',
  'sections.delete': 'You do not have permission to deactivate sections.',
  'subjects.create': 'You do not have permission to create subjects.',
  'subjects.edit': 'You do not have permission to edit subjects.',
  'subjects.delete': 'You do not have permission to deactivate subjects.',
  'subject_groups.create': 'You do not have permission to create subject groups.',
  'subject_groups.edit': 'You do not have permission to edit subject groups.',
  'subject_groups.delete': 'You do not have permission to delete subject groups.',
  'timetable.create': 'You do not have permission to create timetable periods.',
  'timetable.edit': 'You do not have permission to edit timetable periods.',
  'timetable.delete': 'You do not have permission to delete timetable periods.',
  'class_teacher.create': 'You do not have permission to assign class teachers.',
  'class_teacher.edit': 'You do not have permission to edit class teacher assignments.',
  'class_teacher.delete': 'You do not have permission to remove class teacher assignments.',
  'promote_students.create': 'You do not have permission to promote students.',
  'sessions.create': 'You do not have permission to create academic sessions.',
  'sessions.edit': 'You do not have permission to edit academic sessions.',
  'sessions.delete': 'You do not have permission to delete academic sessions.',
  'exams.create': 'You do not have permission to create exams.',
  'exams.edit': 'You do not have permission to edit exams.',
  'exams.delete': 'You do not have permission to delete exams.',
  'exams.submit': 'You cannot submit exams for publication.',
  'exams.approve': 'Only principals or admins can approve exam publication.',
  'fees.manage': 'You do not have permission to manage fees.',
  'attendance.mark': 'You do not have permission to mark attendance.',
};

export function getDeniedMessage(permission: Permission): string {
  return PERMISSION_DENIED_MESSAGES[permission] ?? 'You do not have permission for this action.';
}
