/**
 * Canonical admin route paths — single source for router and navigation.
 * Grouped by module; paths mirror modernized legacy capability map.
 */
export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  adminLogin: '/admin/login',
  staffLogin: '/staff/login',
  dashboard: '/dashboard',
  academics: {
    root: '/academics',
    sessions: '/academics/sessions',
    classes: '/academics/classes',
    sections: '/academics/sections',
    classSections: '/academics/class-sections',
    subjects: '/academics/subjects',
    subjectGroups: '/academics/subject-groups',
    timetable: '/academics/timetable',
    teacherTimetable: '/academics/teacher-timetable',
    classTeacher: '/academics/class-teacher',
    promote: '/academics/promote',
  },
  students: {
    root: '/students',
    categories: '/students/categories',
    houses: '/students/houses',
    disabled: '/students/disabled',
    import: '/students/import',
    onlineAdmission: '/students/online-admission',
    bulkDelete: '/students/bulk-delete',
    disableReason: '/students/disable-reason',
    multiClass: '/students/multi-class',
    detail: (id: number | string) => `/students/${id}`,
  },
  behaviour: {
    root: '/behaviour',
    incidents: '/behaviour/incidents',
    assignments: '/behaviour/assignments',
  },
  staff: {
    root: '/staff',
    attendance: '/staff/attendance',
    payroll: '/staff/payroll',
    leave: '/staff/leave',
    applyLeave: '/staff/apply-leave',
    leaveTypes: '/staff/leave-types',
    leaveAllotments: '/staff/leave-allotments',
    departments: '/staff/departments',
    designations: '/staff/designations',
    ratings: '/staff/ratings',
    disabled: '/staff/disabled',
    payrollIncrement: '/staff/payroll-increment',
    payrollIncrementApprove: '/staff/payroll-increment/approve',
    detail: (id: number | string) => `/staff/${id}`,
  },
  attendance: {
    root: '/attendance',
    mark: '/attendance/mark',
    report: '/attendance/report',
    approveLeave: '/attendance/approve-leave',
    subject: '/attendance/subject',
    periodAttendanceByDate: '/attendance/period-attendance-by-date',
    hostel: '/attendance/hostel',
  },
  fees: {
    root: '/fees',
    collect: '/fees/collect',
    dueSearch: '/fees/due-search',
    paymentSearch: '/fees/payment-search',
    master: '/fees/master',
    feeTypes: '/fees/fee-types',
    feeGroups: '/fees/fee-groups',
    assign: '/fees/assign',
    discounts: '/fees/discounts',
    discountsAssign: '/fees/discounts/assign',
    carryForward: '/fees/carry-forward',
    reminders: '/fees/reminders',
    offlinePayments: '/fees/offline-payments',
    paymentGateways: '/fees/payment-gateways',
    schemeScholarship: '/fees/scheme-scholarship',
    applySchemeScholarship: '/fees/apply-scheme-scholarship',
    positiveFeeAdjustment: '/fees/positive-fee-adjustment',
  },
  examinations: {
    root: '/examinations',
    groups: '/examinations/groups',
    exams: '/examinations/exams',
    schedule: '/examinations/schedule',
    results: '/examinations/results',
    enroll: '/examinations/enroll',
    admitCard: '/examinations/admit-card',
    marksheet: '/examinations/marksheet',
    grades: '/examinations/grades',
    divisions: '/examinations/divisions',
    cbseExams: '/examinations/cbse-exams',
    cbseMarks: '/examinations/cbse-marks',
  },
  frontOffice: {
    root: '/front-office',
    enquiry: '/front-office/enquiry',
    visitors: '/front-office/visitors',
    phoneCalls: '/front-office/phone-calls',
    dispatch: '/front-office/dispatch',
    receive: '/front-office/receive',
    complaints: '/front-office/complaints',
    setup: '/front-office/setup',
  },
  library: {
    root: '/library',
    books: '/library/books',
    issueReturn: '/library/issue-return',
  },
  transport: {
    root: '/transport',
    fees: '/transport/fees',
    pickupPoints: '/transport/pickup-points',
    routes: '/transport/routes',
    vehicles: '/transport/vehicles',
    assignVehicle: '/transport/assign-vehicle',
    routePickupPoints: '/transport/route-pickup-points',
    studentFees: '/transport/student-fees',
  },
  hostel: {
    root: '/hostel',
    rooms: '/hostel/rooms',
    roomTypes: '/hostel/room-types',
    hostels: '/hostel/buildings',
  },
  inventory: {
    root: '/inventory',
    issue: '/inventory/issue',
    stock: '/inventory/stock',
    items: '/inventory/items',
    categories: '/inventory/categories',
    stores: '/inventory/stores',
    suppliers: '/inventory/suppliers',
  },
  homework: {
    root: '/homework',
    assignments: '/homework/assignments',
    daily: '/homework/daily',
  },
  communicate: {
    root: '/communicate',
    notices: '/communicate/notices',
    emailSms: '/communicate/email-sms',
    sendEmail: '/communicate/send-email',
    sendSms: '/communicate/send-sms',
    emailSmsLog: '/communicate/email-sms-log',
    scheduleLog: '/communicate/schedule-log',
    bulkEmail: '/communicate/bulk-email',
    emailTemplate: '/communicate/email-template',
    smsTemplate: '/communicate/sms-template',
  },
  downloadCenter: {
    root: '/download-center',
    contentTypes: '/download-center/content-types',
    content: '/download-center/content',
    videos: '/download-center/videos',
    shareContent: '/download-center/share-content',
  },
  lessonPlan: {
    root: '/lesson-plan',
    manage: '/lesson-plan/manage',
    syllabusStatus: '/lesson-plan/syllabus-status',
    lessons: '/lesson-plan/lessons',
    topics: '/lesson-plan/topics',
    copy: '/lesson-plan/copy-old-lessons',
  },
  onlineExams: {
    root: '/online-examinations',
    exams: '/online-examinations/exams',
    questionBank: '/online-examinations/question-bank',
  },
  income: {
    root: '/income',
    list: '/income/list',
    heads: '/income/heads',
    search: '/income/search',
  },
  expense: {
    root: '/expense',
    list: '/expense/list',
    heads: '/expense/heads',
    search: '/expense/search',
  },
  reports: {
    root: '/reports',
    hub: '/reports/hub',
    students: '/reports/students',
    attendance: '/reports/attendance',
    fees: '/reports/fees',
    examinations: '/reports/examinations',
    finance: '/reports/finance',
    library: '/reports/library',
    inventory: '/reports/inventory',
    hr: '/reports/hr',
    transport: '/reports/transport',
    homework: '/reports/homework',
    alumni: '/reports/alumni',
    lessonPlan: '/reports/lesson-plan',
    userLog: '/reports/user-log',
    auditTrail: '/reports/audit-trail',
    onlineExams: '/reports/online-exams',
    timetable: '/reports/timetable',
  },
  certificates: {
    root: '/certificates',
    templates: '/certificates/templates',
    generate: '/certificates/generate',
    studentIdCard: '/certificates/student-id-card',
    generateIdCard: '/certificates/generate-id-card',
    staffIdCard: '/certificates/staff-id-card',
    generateStaffIdCard: '/certificates/generate-staff-id-card',
  },
  alumni: {
    root: '/alumni',
    list: '/alumni/list',
    events: '/alumni/events',
  },
  cms: {
    root: '/cms',
    events: '/cms/events',
    gallery: '/cms/gallery',
    notices: '/cms/notices',
    media: '/cms/media',
    pages: '/cms/pages',
    menus: '/cms/menus',
    banners: '/cms/banners',
    settings: '/cms/settings',
  },
  leads: {
    root: '/leads',
    all: '/leads/all',
    managed: '/leads/managed',
    unmanaged: '/leads/unmanaged',
    campaigns: '/leads/campaigns',
    campaignTypes: '/leads/campaign-types',
    promoters: '/leads/promoters',
    followUpStatus: '/leads/follow-up-status',
    followUps: '/leads/follow-ups',
    reports: '/leads/reports',
    promoterCommissionReport: '/leads/promoter-commission-report',
    briefReports: '/leads/brief-reports',
    callReports: '/leads/call-reports',
    travelReports: '/leads/travel-reports',
  },
  finance: {
    root: '/finance',
    chartOfAccounts: '/finance/chart-of-accounts',
    mapper: '/finance/mapper',
    entries: '/finance/entries',
    groups: '/finance/groups',
    ledgers: '/finance/ledgers',
    reports: '/finance/reports',
    trialBalance: '/finance/reports/trial-balance',
    balanceSheet: '/finance/reports/balance-sheet',
    profitLoss: '/finance/reports/profit-loss',
    ledgerStatement: '/finance/reports/ledger-statement',
    ledgerEntries: '/finance/reports/ledger-entries',
    reconciliation: '/finance/reports/reconciliation',
  },
  settings: {
    root: '/settings',
    general: '/settings/general',
    languages: '/settings/languages',
    currency: '/settings/currency',
    notifications: '/settings/notifications',
    sms: '/settings/sms',
    email: '/settings/email',
    paymentMethods: '/settings/payment-methods',
    printHeaderFooter: '/settings/print-header-footer',
    roles: '/settings/roles',
    users: '/settings/users',
    modules: '/settings/modules',
    customFields: '/settings/custom-fields',
    captcha: '/settings/captcha',
    systemFields: '/settings/system-fields',
    onlineAdmission: '/settings/online-admission',
    sidebarMenu: '/settings/sidebar-menu',
    backup: '/settings/backup',
    fileTypes: '/settings/file-types',
  },
  lms: {
    root: '/lms',
    courses: {
      root: '/lms/courses',
      new: '/lms/courses/new',
      edit: (id: number | string) => `/lms/courses/${id}/edit`,
    },
  },
  notFound: '*',
} as const;

/** @deprecated Use ROUTES.academics.sessions — kept for redirects. */
export const LEGACY_SETTINGS_SESSIONS = '/settings/sessions';
