from django.db import models


class SchSettings(models.Model):
    """Maps to `sch_settings` in db_current."""

    id = models.IntegerField(primary_key=True)
    base_url = models.CharField(max_length=500, blank=True, null=True)
    folder_path = models.TextField(blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    biometric = models.IntegerField(blank=True, null=True, default=0)
    biometric_device = models.TextField(blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    lang_id = models.IntegerField(blank=True, null=True, db_index=True)
    languages = models.CharField(max_length=500)
    dise_code = models.CharField(max_length=50, blank=True, null=True)
    date_format = models.CharField(max_length=50)
    time_format = models.CharField(max_length=255)
    currency = models.CharField(max_length=50)
    currency_symbol = models.CharField(max_length=50)
    is_rtl = models.CharField(max_length=10, blank=True, null=True, default='disabled')
    is_duplicate_fees_invoice = models.CharField(max_length=100, blank=True, null=True, default=0)
    collect_back_date_fees = models.IntegerField()
    single_page_print = models.IntegerField(blank=True, null=True, default=0)
    timezone = models.CharField(max_length=30, blank=True, null=True, default='UTC')
    session_id = models.IntegerField(blank=True, null=True, db_index=True)
    cron_secret_key = models.CharField(max_length=100)
    currency_place = models.CharField(max_length=50, default='before_number')
    currency_format = models.CharField(max_length=20, blank=True, null=True)
    class_teacher = models.CharField(max_length=100)
    start_month = models.CharField(max_length=40)
    attendence_type = models.IntegerField(default=0)
    low_attendance_limit = models.FloatField()
    image = models.CharField(max_length=100, blank=True, null=True)
    admin_logo = models.CharField(max_length=255)
    admin_small_logo = models.CharField(max_length=255)
    admin_login_page_background = models.CharField(max_length=255)
    user_login_page_background = models.CharField(max_length=255)
    theme = models.CharField(max_length=200, default='default.jpg')
    fee_due_days = models.IntegerField(blank=True, null=True, default=0)
    adm_auto_insert = models.IntegerField(default=1)
    adm_prefix = models.CharField(max_length=50, default='ssadm19/20')
    adm_start_from = models.CharField(max_length=11)
    adm_no_digit = models.IntegerField(default=6)
    adm_update_status = models.IntegerField(default=0)
    staffid_auto_insert = models.IntegerField(default=1)
    staffid_prefix = models.CharField(max_length=100, default='staffss/19/20')
    staffid_start_from = models.CharField(max_length=50)
    staffid_no_digit = models.IntegerField(default=6)
    staffid_update_status = models.IntegerField(default=0)
    is_active = models.CharField(max_length=255, blank=True, null=True, default='no')
    online_admission = models.IntegerField(blank=True, null=True, default=0)
    online_admission_payment = models.CharField(max_length=50)
    online_admission_amount = models.TextField()
    online_admission_instruction = models.TextField()
    online_admission_conditions = models.TextField()
    online_admission_application_form = models.CharField(max_length=255, blank=True, null=True)
    exam_result = models.IntegerField()
    is_blood_group = models.IntegerField(default=1)
    is_student_house = models.IntegerField(default=1)
    roll_no = models.IntegerField(default=1)
    category = models.IntegerField()
    religion = models.IntegerField(default=1)
    cast = models.IntegerField(default=1)
    mobile_no = models.IntegerField(default=1)
    student_email = models.IntegerField(default=1)
    admission_date = models.IntegerField(default=1)
    auto_roll_number = models.CharField(max_length=100, blank=True, null=True)
    lastname = models.IntegerField()
    middlename = models.IntegerField(default=1)
    student_photo = models.IntegerField(default=1)
    student_height = models.IntegerField(default=1)
    student_weight = models.IntegerField(default=1)
    measurement_date = models.IntegerField(default=1)
    father_name = models.IntegerField(default=1)
    father_phone = models.IntegerField(default=1)
    father_occupation = models.IntegerField(default=1)
    father_pic = models.IntegerField(default=1)
    mother_name = models.IntegerField(default=1)
    mother_phone = models.IntegerField(default=1)
    mother_occupation = models.IntegerField(default=1)
    mother_pic = models.IntegerField(default=1)
    guardian_name = models.IntegerField()
    guardian_relation = models.IntegerField(default=1)
    guardian_phone = models.IntegerField()
    guardian_email = models.IntegerField(default=1)
    guardian_pic = models.IntegerField(default=1)
    guardian_occupation = models.IntegerField()
    guardian_address = models.IntegerField(default=1)
    current_address = models.IntegerField(default=1)
    permanent_address = models.IntegerField(default=1)
    route_list = models.IntegerField(default=1)
    hostel_id = models.IntegerField(default=1)
    bank_account_no = models.IntegerField(default=1)
    ifsc_code = models.IntegerField()
    bank_name = models.IntegerField()
    national_identification_no = models.IntegerField(default=1)
    local_identification_no = models.IntegerField(default=1)
    rte = models.IntegerField(default=1)
    previous_school_details = models.IntegerField(default=1)
    student_note = models.IntegerField(default=1)
    upload_documents = models.IntegerField(default=1)
    student_barcode = models.IntegerField(default=1)
    staff_designation = models.IntegerField(default=1)
    staff_department = models.IntegerField(default=1)
    staff_last_name = models.IntegerField(default=1)
    staff_father_name = models.IntegerField(default=1)
    staff_mother_name = models.IntegerField(default=1)
    staff_date_of_joining = models.IntegerField(default=1)
    staff_phone = models.IntegerField(default=1)
    staff_emergency_contact = models.IntegerField(default=1)
    staff_marital_status = models.IntegerField(default=1)
    staff_photo = models.IntegerField(default=1)
    staff_current_address = models.IntegerField(default=1)
    staff_permanent_address = models.IntegerField(default=1)
    staff_qualification = models.IntegerField(default=1)
    staff_work_experience = models.IntegerField(default=1)
    staff_note = models.IntegerField(default=1)
    staff_epf_no = models.IntegerField(default=1)
    staff_basic_salary = models.IntegerField(default=1)
    staff_contract_type = models.IntegerField(default=1)
    staff_work_shift = models.IntegerField(default=1)
    staff_work_location = models.IntegerField(default=1)
    staff_leaves = models.IntegerField(default=1)
    staff_account_details = models.IntegerField(default=1)
    staff_social_media = models.IntegerField(default=1)
    staff_upload_documents = models.IntegerField(default=1)
    staff_barcode = models.IntegerField(default=1)
    staff_notification_email = models.CharField(max_length=50)
    mobile_api_url = models.TextField()
    app_primary_color_code = models.CharField(max_length=20, blank=True, null=True)
    app_secondary_color_code = models.CharField(max_length=20, blank=True, null=True)
    admin_mobile_api_url = models.TextField()
    admin_app_primary_color_code = models.CharField(max_length=20)
    admin_app_secondary_color_code = models.CharField(max_length=20)
    app_logo = models.CharField(max_length=250, blank=True, null=True)
    zoom_api_key = models.CharField(max_length=100, blank=True, null=True)
    zoom_api_secret = models.CharField(max_length=100, blank=True, null=True)
    student_profile_edit = models.IntegerField(default=0)
    start_week = models.CharField(max_length=10)
    day_off = models.CharField(max_length=44, blank=True, null=True)
    my_question = models.IntegerField()
    superadmin_restriction = models.CharField(max_length=20)
    student_timeline = models.CharField(max_length=20)
    calendar_event_reminder = models.IntegerField(blank=True, null=True)
    event_reminder = models.CharField(max_length=20)
    student_login = models.CharField(max_length=100, blank=True, null=True)
    parent_login = models.CharField(max_length=100, blank=True, null=True)
    student_panel_login = models.IntegerField(default=1)
    parent_panel_login = models.IntegerField(default=1)
    is_student_feature_lock = models.IntegerField(default=0)
    maintenance_mode = models.IntegerField(default=0)
    lock_grace_period = models.IntegerField(default=0)
    is_offline_fee_payment = models.IntegerField(default=0)
    google_map_api = models.TextField(blank=True, null=True)
    scan_code_type = models.CharField(max_length=44)
    offline_bank_payment_instruction = models.TextField()
    created_at = models.DateTimeField()
    updated_at = models.DateField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    lng = models.FloatField(blank=True, null=True)
    letter_head = models.TextField()
    is_online_payment_lock = models.IntegerField(blank=True, null=True)
    online_payment_charges_percent = models.TextField(blank=True, null=True)
    test = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = "sch_settings"

    def __str__(self):
        return f"SchSettings {self.pk}"
