# Generated by Django 5.1.15 on 2026-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('childs', models.TextField()),
                ('role', models.CharField(max_length=30)),
                ('lang_id', models.IntegerField()),
                ('currency_id', models.IntegerField(blank=True, default=0, null=True)),
                ('verification_code', models.CharField(max_length=200)),
                ('is_active', models.CharField(blank=True, default='yes', max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'captcha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_notification_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('role_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notification_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('enable_view', models.IntegerField(blank=True, default=0, null=True)),
                ('enable_add', models.IntegerField(blank=True, default=0, null=True)),
                ('enable_edit', models.IntegerField(blank=True, default=0, null=True)),
                ('enable_delete', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'permission category',
                'verbose_name_plural': 'permission categories',
                'db_table': 'permission_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_code', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(blank=True, default=0, null=True)),
                ('system', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'permission group',
                'verbose_name_plural': 'permission groups',
                'db_table': 'permission_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_code', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.IntegerField()),
                ('student', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'permission student',
                'verbose_name_plural': 'permission students',
                'db_table': 'permission_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.IntegerField(blank=True, default=0, null=True)),
                ('is_system', models.IntegerField(default=0)),
                ('is_superadmin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.IntegerField(blank=True, null=True)),
                ('can_add', models.IntegerField(blank=True, null=True)),
                ('can_edit', models.IntegerField(blank=True, null=True)),
                ('can_delete', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_central', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
                'db_table': 'roles_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'staff role',
                'verbose_name_plural': 'staff roles',
                'db_table': 'staff_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user authentication token',
                'verbose_name_plural': 'user authentication tokens',
                'db_table': 'users_authentication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('class_section_id', models.IntegerField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('login_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'user log',
                'verbose_name_plural': 'user logs',
                'db_table': 'userlog',
                'managed': False,
            },
        ),
    ]
