import {
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  CalendarCheck,
  ClipboardList,
  CreditCard,
  Download,
  FileText,
  GraduationCap,
  Home,
  IndianRupee,
  Landmark,
  LayoutDashboard,
  Library,
  Mail,
  Megaphone,
  Package,
  Receipt,
  Settings,
  Target,
  UserPlus,
  Users,
  Wallet,
} from 'lucide-react';
import { ROUTES } from '@constants/routes';
import type { NavItem, NavSection } from '@app-types/navigation';

export const NAV_SECTION_LABELS: Record<Exclude<NavSection, 'main'>, string> = {
  people: 'PEOPLE',
  academics: 'ACADEMICS',
  operations: 'OPERATIONS',
  finance: 'FINANCE',
  insights: 'INSIGHTS',
  system: 'SYSTEM',
};

/** Modernized admin navigation derived from legacy capability map. */
export const ADMIN_NAV: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: ROUTES.dashboard,
    icon: LayoutDashboard,
    section: 'main',
    permissionKeys: ['dashboard'],
  },
  {
    id: 'academics',
    label: 'Academics',
    path: ROUTES.academics.root,
    icon: GraduationCap,
    section: 'academics',
    permissionKeys: ['class', 'section', 'subject', 'subject_group', 'session_setting'],
    children: [
      {
        id: 'academics-sessions',
        label: 'Sessions',
        path: ROUTES.academics.sessions,
        permissionKeys: ['session_setting'],
      },
      {
        id: 'academics-classes',
        label: 'Classes',
        path: ROUTES.academics.classes,
        permissionKeys: ['class'],
      },
      {
        id: 'academics-sections',
        label: 'Sections',
        path: ROUTES.academics.sections,
        permissionKeys: ['section'],
      },
      {
        id: 'academics-class-sections',
        label: 'Class Sections',
        path: ROUTES.academics.classSections,
        permissionKeys: ['class'],
      },
      {
        id: 'academics-subjects',
        label: 'Subjects',
        path: ROUTES.academics.subjects,
        permissionKeys: ['subject'],
      },
      {
        id: 'academics-subject-groups',
        label: 'Subject Groups',
        path: ROUTES.academics.subjectGroups,
        permissionKeys: ['subject_group'],
      },
      {
        id: 'academics-timetable',
        label: 'Timetable',
        path: ROUTES.academics.timetable,
        permissionKeys: ['class_timetable'],
      },
      {
        id: 'academics-teacher-timetable',
        label: 'Teacher Timetable',
        path: ROUTES.academics.teacherTimetable,
        permissionKeys: ['teachers_time_table'],
      },
      {
        id: 'academics-class-teacher',
        label: 'Class Teacher',
        path: ROUTES.academics.classTeacher,
        permissionKeys: ['assign_class_teacher'],
      },
      {
        id: 'academics-promote',
        label: 'Promote Students',
        path: ROUTES.academics.promote,
        permissionKeys: ['promote_student'],
      },
    ],
  },
  {
    id: 'students',
    label: 'Students',
    path: ROUTES.students.root,
    icon: Users,
    section: 'people',
    permissionKeys: ['student'],
    children: [
      {
        id: 'students-directory',
        label: 'Student Directory',
        path: ROUTES.students.root,
        permissionKeys: ['student'],
      },
      {
        id: 'students-categories',
        label: 'Categories',
        path: ROUTES.students.categories,
        permissionKeys: ['student_categories'],
      },
      {
        id: 'students-houses',
        label: 'Houses',
        path: ROUTES.students.houses,
        permissionKeys: ['student_houses'],
      },
      {
        id: 'students-disabled',
        label: 'Disabled Students',
        path: ROUTES.students.disabled,
        permissionKeys: ['disable_student'],
      },
      {
        id: 'students-import',
        label: 'Import Students',
        path: ROUTES.students.import,
        permissionKeys: ['import_student'],
      },
      {
        id: 'students-online-admission',
        label: 'Online Admission',
        path: ROUTES.students.onlineAdmission,
        permissionKeys: ['online_admission'],
      },
    ],
  },
  {
    id: 'staff',
    label: 'Staff',
    path: ROUTES.staff.root,
    icon: Briefcase,
    section: 'people',
    permissionKeys: ['staff'],
    children: [
      {
        id: 'staff-directory',
        label: 'Staff Directory',
        path: ROUTES.staff.root,
        permissionKeys: ['staff'],
      },
      {
        id: 'staff-attendance',
        label: 'Attendance',
        path: ROUTES.staff.attendance,
        permissionKeys: ['staff_attendance'],
      },
      {
        id: 'staff-payroll',
        label: 'Payroll',
        path: ROUTES.staff.payroll,
        permissionKeys: ['staff_payroll'],
      },
      {
        id: 'staff-leave',
        label: 'Leave Requests',
        path: ROUTES.staff.leave,
        permissionKeys: ['approve_leave_request'],
      },
      {
        id: 'staff-leave-types',
        label: 'Leave Types',
        path: ROUTES.staff.leaveTypes,
        permissionKeys: ['leave_types'],
      },
      {
        id: 'staff-departments',
        label: 'Departments',
        path: ROUTES.staff.departments,
        permissionKeys: ['department'],
      },
      {
        id: 'staff-designations',
        label: 'Designations',
        path: ROUTES.staff.designations,
        permissionKeys: ['designation'],
      },
    ],
  },
  {
    id: 'attendance',
    label: 'Attendance',
    path: ROUTES.attendance.root,
    icon: CalendarCheck,
    section: 'operations',
    permissionKeys: ['student_attendance'],
    children: [
      {
        id: 'attendance-mark',
        label: 'Mark Attendance',
        path: ROUTES.attendance.mark,
        permissionKeys: ['student_attendance'],
      },
      {
        id: 'attendance-report',
        label: 'Attendance Report',
        path: ROUTES.attendance.report,
        permissionKeys: ['attendance_report'],
      },
      {
        id: 'attendance-approve-leave',
        label: 'Approve Leave',
        path: ROUTES.attendance.approveLeave,
        permissionKeys: ['approve_leave'],
      },
      {
        id: 'attendance-subject',
        label: 'Subject Attendance',
        path: ROUTES.attendance.subject,
        permissionKeys: ['subject_attendance'],
      },
    ],
  },
  {
    id: 'fees',
    label: 'Fees',
    path: ROUTES.fees.root,
    icon: IndianRupee,
    section: 'operations',
    permissionKeys: ['collect_fees', 'fees_master'],
    children: [
      {
        id: 'fees-collect',
        label: 'Collect Fees',
        path: ROUTES.fees.collect,
        permissionKeys: ['collect_fees'],
      },
      {
        id: 'fees-due-search',
        label: 'Search Due Fees',
        path: ROUTES.fees.dueSearch,
        permissionKeys: ['search_due_fees'],
      },
      {
        id: 'fees-payment-search',
        label: 'Search Payments',
        path: ROUTES.fees.paymentSearch,
        permissionKeys: ['search_fees_payment'],
      },
      {
        id: 'fees-master',
        label: 'Fees Master',
        path: ROUTES.fees.master,
        permissionKeys: ['fees_master'],
      },
      {
        id: 'fees-types',
        label: 'Fee Types',
        path: ROUTES.fees.feeTypes,
        permissionKeys: ['feetype'],
      },
      {
        id: 'fees-groups',
        label: 'Fee Groups',
        path: ROUTES.fees.feeGroups,
        permissionKeys: ['fees_group'],
      },
      {
        id: 'fees-assign',
        label: 'Assign Fees',
        path: ROUTES.fees.assign,
        permissionKeys: ['fees_group_assign'],
      },
      {
        id: 'fees-discounts',
        label: 'Fee Discounts',
        path: ROUTES.fees.discounts,
        permissionKeys: ['fees_discount'],
      },
      {
        id: 'fees-carry-forward',
        label: 'Carry Forward',
        path: ROUTES.fees.carryForward,
        permissionKeys: ['fees_forward'],
      },
      {
        id: 'fees-reminders',
        label: 'Fee Reminders',
        path: ROUTES.fees.reminders,
        permissionKeys: ['fees_reminder'],
      },
      {
        id: 'fees-offline',
        label: 'Offline Bank Payments',
        path: ROUTES.fees.offlinePayments,
        permissionKeys: ['offline_bank_payments'],
      },
    ],
  },
  {
    id: 'examinations',
    label: 'Examinations',
    path: ROUTES.examinations.root,
    icon: BookOpen,
    section: 'operations',
    permissionKeys: ['exam_group', 'exam_schedule', 'exam_result'],
    children: [
      {
        id: 'exams-groups',
        label: 'Exam Groups',
        path: ROUTES.examinations.groups,
        permissionKeys: ['exam_group'],
      },
      {
        id: 'exams-list',
        label: 'Exams',
        path: ROUTES.examinations.exams,
        permissionKeys: ['exam_group'],
      },
      {
        id: 'exams-schedule',
        label: 'Exam Schedule',
        path: ROUTES.examinations.schedule,
        permissionKeys: ['exam_schedule'],
      },
      {
        id: 'exams-results',
        label: 'Exam Results',
        path: ROUTES.examinations.results,
        permissionKeys: ['exam_result'],
      },
      {
        id: 'exams-admit-card',
        label: 'Admit Card',
        path: ROUTES.examinations.admitCard,
        permissionKeys: ['admit_card'],
      },
      {
        id: 'exams-marksheet',
        label: 'Marksheet',
        path: ROUTES.examinations.marksheet,
        permissionKeys: ['marksheet'],
      },
      {
        id: 'exams-grades',
        label: 'Marks Grade',
        path: ROUTES.examinations.grades,
        permissionKeys: ['marks_grade'],
      },
      {
        id: 'exams-divisions',
        label: 'Marks Division',
        path: ROUTES.examinations.divisions,
        permissionKeys: ['marks_division'],
      },
    ],
  },
  {
    id: 'front-office',
    label: 'Front Office',
    path: ROUTES.frontOffice.root,
    icon: Home,
    section: 'operations',
    permissionKeys: ['admission_enquiry', 'visitor_book'],
    children: [
      {
        id: 'fo-enquiry',
        label: 'Admission Enquiry',
        path: ROUTES.frontOffice.enquiry,
        permissionKeys: ['admission_enquiry'],
      },
      {
        id: 'fo-visitors',
        label: 'Visitor Book',
        path: ROUTES.frontOffice.visitors,
        permissionKeys: ['visitor_book'],
      },
      {
        id: 'fo-calls',
        label: 'Phone Call Log',
        path: ROUTES.frontOffice.phoneCalls,
        permissionKeys: ['phone_call_log'],
      },
      {
        id: 'fo-dispatch',
        label: 'Postal Dispatch',
        path: ROUTES.frontOffice.dispatch,
        permissionKeys: ['postal_dispatch'],
      },
      {
        id: 'fo-receive',
        label: 'Postal Receive',
        path: ROUTES.frontOffice.receive,
        permissionKeys: ['postal_receive'],
      },
      {
        id: 'fo-complaints',
        label: 'Complaints',
        path: ROUTES.frontOffice.complaints,
        permissionKeys: ['complaint'],
      },
      {
        id: 'fo-visitor-purpose',
        label: 'Visitor Purpose',
        path: ROUTES.frontOffice.visitorPurpose,
        permissionKeys: ['setup_front_office'],
      },
    ],
  },
  {
    id: 'library',
    label: 'Library',
    path: ROUTES.library.root,
    icon: Library,
    section: 'operations',
    permissionKeys: ['books', 'issue_return'],
    children: [
      {
        id: 'library-books',
        label: 'Book List',
        path: ROUTES.library.books,
        permissionKeys: ['books'],
      },
      {
        id: 'library-issue',
        label: 'Issue & Return',
        path: ROUTES.library.issueReturn,
        permissionKeys: ['issue_return'],
      },
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    path: ROUTES.transport.root,
    icon: Bus,
    section: 'operations',
    permissionKeys: ['transport_fees', 'routes'],
    children: [
      {
        id: 'transport-fees',
        label: 'Transport Fees',
        path: ROUTES.transport.fees,
        permissionKeys: ['transport_fees'],
      },
      {
        id: 'transport-pickup',
        label: 'Pickup Points',
        path: ROUTES.transport.pickupPoints,
        permissionKeys: ['pickup_point'],
      },
      {
        id: 'transport-routes',
        label: 'Routes',
        path: ROUTES.transport.routes,
        permissionKeys: ['routes'],
      },
      {
        id: 'transport-vehicles',
        label: 'Vehicles',
        path: ROUTES.transport.vehicles,
        permissionKeys: ['vehicle'],
      },
      {
        id: 'transport-assign',
        label: 'Assign Vehicle',
        path: ROUTES.transport.assignVehicle,
        permissionKeys: ['assign_vehicle'],
      },
    ],
  },
  {
    id: 'hostel',
    label: 'Hostel',
    path: ROUTES.hostel.root,
    icon: Building2,
    section: 'operations',
    permissionKeys: ['hostel_rooms', 'hostel'],
    children: [
      {
        id: 'hostel-rooms',
        label: 'Hostel Rooms',
        path: ROUTES.hostel.rooms,
        permissionKeys: ['hostel_rooms'],
      },
      {
        id: 'hostel-room-types',
        label: 'Room Types',
        path: ROUTES.hostel.roomTypes,
        permissionKeys: ['hostel_room_type'],
      },
      {
        id: 'hostel-buildings',
        label: 'Hostels',
        path: ROUTES.hostel.hostels,
        permissionKeys: ['hostel'],
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    path: ROUTES.inventory.root,
    icon: Package,
    section: 'operations',
    permissionKeys: ['item', 'item_stock'],
    children: [
      {
        id: 'inventory-issue',
        label: 'Issue Item',
        path: ROUTES.inventory.issue,
        permissionKeys: ['issue_item'],
      },
      {
        id: 'inventory-stock',
        label: 'Add Item Stock',
        path: ROUTES.inventory.stock,
        permissionKeys: ['item_stock'],
      },
      {
        id: 'inventory-items',
        label: 'Items',
        path: ROUTES.inventory.items,
        permissionKeys: ['item'],
      },
      {
        id: 'inventory-categories',
        label: 'Item Categories',
        path: ROUTES.inventory.categories,
        permissionKeys: ['item_category'],
      },
      {
        id: 'inventory-stores',
        label: 'Item Stores',
        path: ROUTES.inventory.stores,
        permissionKeys: ['item_store'],
      },
      {
        id: 'inventory-suppliers',
        label: 'Suppliers',
        path: ROUTES.inventory.suppliers,
        permissionKeys: ['item_supplier'],
      },
    ],
  },
  {
    id: 'homework',
    label: 'Homework',
    path: ROUTES.homework.root,
    icon: ClipboardList,
    section: 'operations',
    permissionKeys: ['homework', 'daily_assignment'],
    children: [
      {
        id: 'homework-assignments',
        label: 'Homework',
        path: ROUTES.homework.assignments,
        permissionKeys: ['homework'],
      },
      {
        id: 'homework-daily',
        label: 'Daily Assignment',
        path: ROUTES.homework.daily,
        permissionKeys: ['daily_assignment'],
      },
    ],
  },
  {
    id: 'communicate',
    label: 'Communicate',
    path: ROUTES.communicate.root,
    icon: Mail,
    section: 'operations',
    permissionKeys: ['notice_board', 'email_sms'],
    children: [
      {
        id: 'communicate-notices',
        label: 'Notice Board',
        path: ROUTES.communicate.notices,
        permissionKeys: ['notice_board'],
      },
      {
        id: 'communicate-email-sms',
        label: 'Send Email / SMS',
        path: ROUTES.communicate.emailSms,
        permissionKeys: ['email_sms'],
      },
      {
        id: 'communicate-bulk',
        label: 'Bulk Email to Students',
        path: ROUTES.communicate.bulkEmail,
        permissionKeys: ['email_sms'],
      },
    ],
  },
  {
    id: 'download-center',
    label: 'Download Center',
    path: ROUTES.downloadCenter.root,
    icon: Download,
    section: 'operations',
    permissionKeys: ['upload_content', 'video_tutorial'],
    children: [
      {
        id: 'download-types',
        label: 'Content Types',
        path: ROUTES.downloadCenter.contentTypes,
        permissionKeys: ['upload_content'],
      },
      {
        id: 'download-content',
        label: 'Upload Content',
        path: ROUTES.downloadCenter.content,
        permissionKeys: ['upload_content'],
      },
      {
        id: 'download-videos',
        label: 'Video Tutorials',
        path: ROUTES.downloadCenter.videos,
        permissionKeys: ['video_tutorial'],
      },
    ],
  },
  {
    id: 'lesson-plan',
    label: 'Lesson Plan',
    path: ROUTES.lessonPlan.root,
    icon: FileText,
    section: 'operations',
    permissionKeys: ['lesson_plan', 'manage_syllabus_status'],
    children: [
      {
        id: 'lesson-syllabus',
        label: 'Syllabus Status',
        path: ROUTES.lessonPlan.syllabusStatus,
        permissionKeys: ['manage_syllabus_status'],
      },
      {
        id: 'lesson-lessons',
        label: 'Lessons & Topics',
        path: ROUTES.lessonPlan.lessons,
        permissionKeys: ['lesson_plan'],
      },
    ],
  },
  {
    id: 'online-exams',
    label: 'Online Examinations',
    path: ROUTES.onlineExams.root,
    icon: Target,
    section: 'operations',
    permissionKeys: ['online_examination', 'question_bank'],
    children: [
      {
        id: 'online-exams-setup',
        label: 'Online Exam',
        path: ROUTES.onlineExams.exams,
        permissionKeys: ['online_examination'],
      },
      {
        id: 'online-exams-questions',
        label: 'Question Bank',
        path: ROUTES.onlineExams.questionBank,
        permissionKeys: ['question_bank'],
      },
    ],
  },
  {
    id: 'income',
    label: 'Income',
    path: ROUTES.income.root,
    icon: Wallet,
    section: 'finance',
    permissionKeys: ['income', 'income_head'],
    children: [
      {
        id: 'income-list',
        label: 'Add Income',
        path: ROUTES.income.list,
        permissionKeys: ['income'],
      },
      {
        id: 'income-heads',
        label: 'Income Heads',
        path: ROUTES.income.heads,
        permissionKeys: ['income_head'],
      },
    ],
  },
  {
    id: 'expense',
    label: 'Expense',
    path: ROUTES.expense.root,
    icon: Receipt,
    section: 'finance',
    permissionKeys: ['expense', 'expense_head'],
    children: [
      {
        id: 'expense-list',
        label: 'Add Expense',
        path: ROUTES.expense.list,
        permissionKeys: ['expense'],
      },
      {
        id: 'expense-heads',
        label: 'Expense Heads',
        path: ROUTES.expense.heads,
        permissionKeys: ['expense_head'],
      },
    ],
  },
  {
    id: 'finance',
    label: 'Account Finance',
    path: ROUTES.finance.root,
    icon: Landmark,
    section: 'finance',
    permissionKeys: ['account_finance'],
    children: [
      {
        id: 'finance-coa',
        label: 'Chart of Accounts',
        path: ROUTES.finance.chartOfAccounts,
        permissionKeys: ['account_finance'],
      },
      {
        id: 'finance-mapper',
        label: 'Account Mapper',
        path: ROUTES.finance.mapper,
        permissionKeys: ['account_finance'],
      },
      {
        id: 'finance-entries',
        label: 'Journal Entries',
        path: ROUTES.finance.entries,
        permissionKeys: ['account_finance'],
      },
      {
        id: 'finance-groups',
        label: 'Ledger Groups',
        path: ROUTES.finance.groups,
        permissionKeys: ['account_finance'],
      },
      {
        id: 'finance-ledgers',
        label: 'Ledgers',
        path: ROUTES.finance.ledgers,
        permissionKeys: ['account_finance'],
      },
      {
        id: 'finance-reports',
        label: 'Financial Reports',
        path: ROUTES.finance.reports,
        permissionKeys: ['account_finance'],
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    path: ROUTES.reports.root,
    icon: BarChart3,
    section: 'insights',
    permissionKeys: ['student_report', 'attendance_report', 'finance_report'],
    children: [
      {
        id: 'reports-students',
        label: 'Student Reports',
        path: ROUTES.reports.students,
        permissionKeys: ['student_report'],
      },
      {
        id: 'reports-attendance',
        label: 'Attendance Reports',
        path: ROUTES.reports.attendance,
        permissionKeys: ['attendance_report'],
      },
      {
        id: 'reports-fees',
        label: 'Finance & Fees',
        path: ROUTES.reports.fees,
        permissionKeys: ['finance_report'],
      },
      {
        id: 'reports-exams',
        label: 'Exam Reports',
        path: ROUTES.reports.examinations,
        permissionKeys: ['exam_result_report'],
      },
      {
        id: 'reports-finance',
        label: 'Income & Expense',
        path: ROUTES.reports.finance,
        permissionKeys: ['finance_report'],
      },
      {
        id: 'reports-library',
        label: 'Library Reports',
        path: ROUTES.reports.library,
        permissionKeys: ['library_report'],
      },
      {
        id: 'reports-inventory',
        label: 'Inventory Reports',
        path: ROUTES.reports.inventory,
        permissionKeys: ['inventory_report'],
      },
      {
        id: 'reports-hr',
        label: 'HR Reports',
        path: ROUTES.reports.hr,
        permissionKeys: ['staff_report'],
      },
      {
        id: 'reports-transport',
        label: 'Transport & Hostel',
        path: ROUTES.reports.transport,
        permissionKeys: ['transport_report', 'hostel_report'],
      },
      {
        id: 'reports-homework',
        label: 'Homework Reports',
        path: ROUTES.reports.homework,
        permissionKeys: ['homework_report'],
      },
    ],
  },
  {
    id: 'certificates',
    label: 'Certificates',
    path: ROUTES.certificates.root,
    icon: CreditCard,
    section: 'insights',
    permissionKeys: ['certificate', 'student_id_card'],
    children: [
      {
        id: 'cert-templates',
        label: 'Certificate Templates',
        path: ROUTES.certificates.templates,
        permissionKeys: ['certificate'],
      },
      {
        id: 'cert-generate',
        label: 'Generate Certificate',
        path: ROUTES.certificates.generate,
        permissionKeys: ['generate_certificate'],
      },
      {
        id: 'cert-student-id',
        label: 'Student ID Card',
        path: ROUTES.certificates.studentIdCard,
        permissionKeys: ['student_id_card'],
      },
      {
        id: 'cert-generate-id',
        label: 'Generate ID Card',
        path: ROUTES.certificates.generateIdCard,
        permissionKeys: ['generate_id_card'],
      },
      {
        id: 'cert-staff-id',
        label: 'Staff ID Card',
        path: ROUTES.certificates.staffIdCard,
        permissionKeys: ['staff_id_card'],
      },
      {
        id: 'cert-generate-staff-id',
        label: 'Generate Staff ID',
        path: ROUTES.certificates.generateStaffIdCard,
        permissionKeys: ['generate_staff_id_card'],
      },
    ],
  },
  {
    id: 'alumni',
    label: 'Alumni',
    path: ROUTES.alumni.root,
    icon: Megaphone,
    section: 'insights',
    permissionKeys: ['manage_alumni', 'alumni_event'],
    children: [
      {
        id: 'alumni-list',
        label: 'Manage Alumni',
        path: ROUTES.alumni.list,
        permissionKeys: ['manage_alumni'],
      },
      {
        id: 'alumni-events',
        label: 'Alumni Events',
        path: ROUTES.alumni.events,
        permissionKeys: ['alumni_event'],
      },
    ],
  },
  {
    id: 'leads',
    label: 'Lead Management',
    path: ROUTES.leads.root,
    icon: UserPlus,
    section: 'insights',
    permissionKeys: ['lead_manager'],
    children: [
      {
        id: 'leads-all',
        label: 'All Leads',
        path: ROUTES.leads.all,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-campaigns',
        label: 'Campaigns',
        path: ROUTES.leads.campaigns,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-campaign-types',
        label: 'Campaign Types',
        path: ROUTES.leads.campaignTypes,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-promoters',
        label: 'Promoters',
        path: ROUTES.leads.promoters,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-followup-status',
        label: 'Follow-up Status',
        path: ROUTES.leads.followUpStatus,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-followups',
        label: 'Follow-ups',
        path: ROUTES.leads.followUps,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-reports',
        label: 'Reports',
        path: ROUTES.leads.reports,
        permissionKeys: ['lead_manager'],
      },
    ],
  },
  {
    id: 'cms',
    label: 'Front CMS',
    path: ROUTES.cms.root,
    icon: FileText,
    section: 'insights',
    permissionKeys: ['event', 'gallery', 'pages', 'menus'],
    children: [
      { id: 'cms-events', label: 'Events', path: ROUTES.cms.events, permissionKeys: ['event'] },
      {
        id: 'cms-gallery',
        label: 'Gallery',
        path: ROUTES.cms.gallery,
        permissionKeys: ['gallery'],
      },
      { id: 'cms-notices', label: 'Notices', path: ROUTES.cms.notices, permissionKeys: ['notice'] },
      {
        id: 'cms-media',
        label: 'Media Manager',
        path: ROUTES.cms.media,
        permissionKeys: ['media_manager'],
      },
      { id: 'cms-pages', label: 'Pages', path: ROUTES.cms.pages, permissionKeys: ['pages'] },
      { id: 'cms-menus', label: 'Menus', path: ROUTES.cms.menus, permissionKeys: ['menus'] },
      {
        id: 'cms-banners',
        label: 'Banners',
        path: ROUTES.cms.banners,
        permissionKeys: ['banner_images'],
      },
      {
        id: 'cms-settings',
        label: 'CMS Settings',
        path: ROUTES.cms.settings,
        permissionKeys: ['front_cms_setting'],
      },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    path: ROUTES.settings.root,
    icon: Settings,
    section: 'system',
    permissionKeys: ['general_setting', 'roles'],
    children: [
      {
        id: 'settings-general',
        label: 'General Settings',
        path: ROUTES.settings.general,
        permissionKeys: ['general_setting'],
      },
      {
        id: 'settings-languages',
        label: 'Languages',
        path: ROUTES.settings.languages,
        permissionKeys: ['languages'],
      },
      {
        id: 'settings-currency',
        label: 'Currency',
        path: ROUTES.settings.currency,
        permissionKeys: ['currency'],
      },
      {
        id: 'settings-notifications',
        label: 'Notifications',
        path: ROUTES.settings.notifications,
        permissionKeys: ['notification_setting'],
      },
      {
        id: 'settings-sms',
        label: 'SMS Config',
        path: ROUTES.settings.sms,
        permissionKeys: ['sms_setting'],
      },
      {
        id: 'settings-email',
        label: 'Email Config',
        path: ROUTES.settings.email,
        permissionKeys: ['email_setting'],
      },
      {
        id: 'settings-payment',
        label: 'Payment Methods',
        path: ROUTES.settings.paymentMethods,
        permissionKeys: ['payment_methods'],
      },
      {
        id: 'settings-print',
        label: 'Print Header & Footer',
        path: ROUTES.settings.printHeaderFooter,
        permissionKeys: ['print_headerfooter'],
      },
      {
        id: 'settings-roles',
        label: 'Roles & Permissions',
        path: ROUTES.settings.roles,
        permissionKeys: ['roles'],
      },
      {
        id: 'settings-users',
        label: 'User Accounts',
        path: ROUTES.settings.users,
        permissionKeys: ['user_status'],
      },
      {
        id: 'settings-modules',
        label: 'Modules',
        path: ROUTES.settings.modules,
        permissionKeys: ['superadmin'],
      },
      {
        id: 'settings-custom-fields',
        label: 'Custom Fields',
        path: ROUTES.settings.customFields,
        permissionKeys: ['custom_field'],
      },
      {
        id: 'settings-captcha',
        label: 'Captcha',
        path: ROUTES.settings.captcha,
        permissionKeys: ['captcha_setting'],
      },
      {
        id: 'settings-system-fields',
        label: 'System Fields',
        path: ROUTES.settings.systemFields,
        permissionKeys: ['system_field'],
      },
      {
        id: 'settings-online-admission',
        label: 'Online Admission',
        path: ROUTES.settings.onlineAdmission,
        permissionKeys: ['online_admission'],
      },
      {
        id: 'settings-sidebar',
        label: 'Sidebar Menu',
        path: ROUTES.settings.sidebarMenu,
        permissionKeys: ['sidebar_menu'],
      },
      {
        id: 'settings-backup',
        label: 'Backup / Restore',
        path: ROUTES.settings.backup,
        permissionKeys: ['backup'],
      },
      {
        id: 'settings-file-types',
        label: 'File Types',
        path: ROUTES.settings.fileTypes,
        permissionKeys: ['superadmin'],
      },
    ],
  },
];
