import {
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  CalendarCheck,
  ClipboardList,
  CreditCard,
  Download,
  FileBarChart,
  FileText,
  GraduationCap,
  Home,
  IndianRupee,
  Landmark,
  LayoutDashboard,
  Library,
  Mail,
  Megaphone,
  Monitor,
  Package,
  Receipt,
  Settings,
  Target,
  UserPlus,
  Users,
  Wallet,
} from 'lucide-react';
import { ROUTES } from '@constants/routes';
import type { NavItem, NavSection } from '@app-types/navigation';

export const NAV_SECTION_LABELS: Record<Exclude<NavSection, 'main'>, string> = {
  people: 'PEOPLE',
  academics: 'ACADEMICS',
  operations: 'OPERATIONS',
  finance: 'FINANCE',
  insights: 'INSIGHTS',
  system: 'SYSTEM',
};

/** Modernized admin navigation derived from legacy capability map. */
export const ADMIN_NAV: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: ROUTES.dashboard,
    icon: LayoutDashboard,
    section: 'main',
    permissionKeys: ['dashboard'],
  },
  {
    id: 'academics',
    label: 'Academics',
    path: ROUTES.academics.root,
    icon: GraduationCap,
    section: 'academics',
    permissionKeys: ['class', 'section', 'subject', 'subject_group', 'session_setting'],
    children: [
      {
        id: 'academics-sessions',
        label: 'Sessions',
        path: ROUTES.academics.sessions,
        permissionKeys: ['session_setting'],
      },
      {
        id: 'academics-classes',
        label: 'Classes',
        path: ROUTES.academics.classes,
        permissionKeys: ['class'],
      },
      {
        id: 'academics-sections',
        label: 'Sections',
        path: ROUTES.academics.sections,
        permissionKeys: ['section'],
      },
      {
        id: 'academics-class-sections',
        label: 'Class Sections',
        path: ROUTES.academics.classSections,
        permissionKeys: ['class'],
      },
      {
        id: 'academics-subjects',
        label: 'Subjects',
        path: ROUTES.academics.subjects,
        permissionKeys: ['subject'],
      },
      {
        id: 'academics-subject-groups',
        label: 'Groups',
        path: ROUTES.academics.subjectGroups,
        permissionKeys: ['subject_group'],
      },
      {
        id: 'academics-timetable',
        label: 'Timetable',
        path: ROUTES.academics.timetable,
        permissionKeys: ['class_timetable'],
      },
      {
        id: 'academics-teacher-timetable',
        label: 'Teacher Timetable',
        path: ROUTES.academics.teacherTimetable,
        permissionKeys: ['teachers_time_table'],
      },
      {
        id: 'academics-class-teacher',
        label: 'Class Teacher',
        path: ROUTES.academics.classTeacher,
        permissionKeys: ['assign_class_teacher'],
      },
      {
        id: 'academics-promote',
        label: 'Promote Students',
        path: ROUTES.academics.promote,
        permissionKeys: ['promote_student'],
      },
    ],
  },
  {
    id: 'higher-education',
    label: 'Higher Education',
    icon: GraduationCap,
    section: 'academics',
    permissionKeys: ['higher_education'],
    comingSoon: true,
    children: [
      { id: 'hedu-programs', label: 'Programs', comingSoon: true },
      { id: 'hedu-batches', label: 'Batches', comingSoon: true },
      { id: 'hedu-courses', label: 'Courses', comingSoon: true },
      { id: 'hedu-course-mapping', label: 'Course Mapping', comingSoon: true },
      { id: 'hedu-course-period-mapping', label: 'Course Period Mapping', comingSoon: true },
      { id: 'hedu-co-outcomes', label: 'CO Outcomes', comingSoon: true },
      { id: 'hedu-po-outcomes', label: 'PO Outcomes', comingSoon: true },
      { id: 'hedu-outcomes-mapping', label: 'Outcomes Mapping', comingSoon: true },
      { id: 'hedu-copo-mapping', label: 'COPO Mapping', comingSoon: true },
      { id: 'hedu-blooms-competency', label: 'Blooms Competency', comingSoon: true },
      { id: 'hedu-add-questions', label: 'Add Questions', comingSoon: true },
      { id: 'hedu-exam', label: 'Exam', comingSoon: true },
    ],
  },
  {
    id: 'students',
    label: 'Students',
    path: ROUTES.students.root,
    icon: Users,
    section: 'people',
    permissionKeys: ['student'],
    children: [
      {
        id: 'students-directory',
        label: 'Student Directory',
        path: ROUTES.students.root,
        permissionKeys: ['student'],
      },
      {
        id: 'students-admission',
        label: 'Student Admission',
        path: ROUTES.students.root,
        permissionKeys: ['student'],
      },
      {
        id: 'students-categories',
        label: 'Categories',
        path: ROUTES.students.categories,
        permissionKeys: ['student_categories'],
      },
      {
        id: 'students-houses',
        label: 'Houses',
        path: ROUTES.students.houses,
        permissionKeys: ['student_houses'],
      },
      {
        id: 'students-disabled',
        label: 'Disabled Students',
        path: ROUTES.students.disabled,
        permissionKeys: ['student'],
      },
      {
        id: 'students-import',
        label: 'Import Students',
        path: ROUTES.students.import,
        permissionKeys: ['import_student'],
      },
      {
        id: 'students-online-admission',
        label: 'Online Admission',
        path: ROUTES.students.onlineAdmission,
        permissionKeys: ['online_admission'],
      },
      {
        id: 'students-bulk-delete',
        label: 'Bulk Delete',
        path: ROUTES.students.bulkDelete,
        permissionKeys: ['student'],
      },
      {
        id: 'students-disable-reason',
        label: 'Disable Reason',
        path: ROUTES.students.disableReason,
        permissionKeys: ['disable_reason'],
      },
      {
        id: 'students-multi-class',
        label: 'Multi Class Student',
        path: ROUTES.students.multiClass,
        permissionKeys: ['multi_class_student'],
      },
    ],
  },
  {
    id: 'behaviour',
    label: 'Behaviour Records',
    path: ROUTES.behaviour.incidents,
    icon: ClipboardList,
    section: 'people',
    permissionKeys: ['behaviour_records'],
    children: [
      {
        id: 'behaviour-incidents',
        label: 'Incident Types',
        path: ROUTES.behaviour.incidents,
        permissionKeys: ['behaviour_records_incident'],
      },
      {
        id: 'behaviour-assignments',
        label: 'Assign Incidents',
        path: ROUTES.behaviour.assignments,
        permissionKeys: ['behaviour_records_assign_incident'],
      },
    ],
  },
  {
    id: 'staff',
    label: 'Staff',
    path: ROUTES.staff.root,
    icon: Briefcase,
    section: 'people',
    permissionKeys: ['staff'],
    children: [
      {
        id: 'staff-directory',
        label: 'Staff Directory',
        path: ROUTES.staff.root,
        permissionKeys: ['staff'],
      },
      {
        id: 'staff-attendance',
        label: 'Attendance',
        path: ROUTES.staff.attendance,
        permissionKeys: ['staff_attendance'],
      },
      {
        id: 'staff-payroll',
        label: 'Payroll',
        path: ROUTES.staff.payroll,
        permissionKeys: ['staff_payroll'],
      },
      {
        id: 'staff-leave',
        label: 'Leave Requests',
        path: ROUTES.staff.leave,
        permissionKeys: ['approve_leave_request'],
      },
      {
        id: 'staff-leave-types',
        label: 'Leave Types',
        path: ROUTES.staff.leaveTypes,
        permissionKeys: ['leave_types'],
      },
      {
        id: 'staff-leave-allotments',
        label: 'Leave Allotments',
        path: ROUTES.staff.leaveAllotments,
        permissionKeys: ['staff'],
      },
      {
        id: 'staff-apply-leave',
        label: 'Apply Leave',
        path: ROUTES.staff.leave,
        comingSoon: true,
        permissionKeys: ['apply_leave'],
      },
      {
        id: 'staff-rating',
        label: 'Teachers Rating',
        path: ROUTES.staff.ratings,
        permissionKeys: ['teachers_rating'],
      },
      {
        id: 'staff-departments',
        label: 'Departments',
        path: ROUTES.staff.departments,
        permissionKeys: ['department'],
      },
      {
        id: 'staff-designations',
        label: 'Designations',
        path: ROUTES.staff.designations,
        permissionKeys: ['designation'],
      },
      {
        id: 'staff-disabled',
        label: 'Disabled Staff',
        path: ROUTES.staff.root,
        comingSoon: true,
        permissionKeys: ['disable_staff'],
      },
      {
        id: 'staff-payroll-increment',
        label: 'Payroll Increment',
        comingSoon: true,
        permissionKeys: ['staff'],
      },
      {
        id: 'staff-payroll-increment-approve',
        label: 'Approve Payroll Increment',
        comingSoon: true,
        permissionKeys: ['staff'],
      },
    ],
  },
  {
    id: 'attendance',
    label: 'Attendance',
    path: ROUTES.attendance.root,
    icon: CalendarCheck,
    section: 'operations',
    permissionKeys: [
      'attendance.mark',
      'attendance.report',
      'attendance.approve_leave',
      'attendance.subject',
    ],
    children: [
      {
        id: 'attendance-mark',
        label: 'Mark Attendance',
        path: ROUTES.attendance.mark,
        permissionKeys: ['attendance.mark'],
      },
      {
        id: 'attendance-report',
        label: 'Attendance Report',
        path: ROUTES.attendance.report,
        permissionKeys: ['attendance.report'],
      },
      {
        id: 'attendance-approve-leave',
        label: 'Approve Leave',
        path: ROUTES.attendance.approveLeave,
        permissionKeys: ['attendance.approve_leave'],
      },
      {
        id: 'attendance-subject',
        label: 'Subject Attendance',
        path: ROUTES.attendance.subject,
        permissionKeys: ['attendance.subject'],
      },
      {
        id: 'attendance-period-by-date',
        label: 'Period Attendance By Date',
        path: ROUTES.attendance.periodAttendanceByDate,
        permissionKeys: ['attendance.report'],
      },
      {
        id: 'attendance-hostel',
        label: 'Hostel Attendance',
        path: ROUTES.attendance.hostel,
        permissionKeys: ['attendance.mark'],
      },
    ],
  },
  {
    id: 'fees',
    label: 'Fees',
    path: ROUTES.fees.root,
    icon: IndianRupee,
    section: 'operations',
    permissionKeys: ['collect_fees', 'fees_master'],
    children: [
      {
        id: 'fees-collect',
        label: 'Collect Fees',
        path: ROUTES.fees.collect,
        permissionKeys: ['collect_fees'],
      },
      {
        id: 'fees-due-search',
        label: 'Search Due Fees',
        path: ROUTES.fees.dueSearch,
        permissionKeys: ['search_due_fees'],
      },
      {
        id: 'fees-payment-search',
        label: 'Search Payments',
        path: ROUTES.fees.paymentSearch,
        permissionKeys: ['search_fees_payment'],
      },
      {
        id: 'fees-master',
        label: 'Fees Master',
        path: ROUTES.fees.master,
        permissionKeys: ['fees_master'],
      },
      {
        id: 'fees-types',
        label: 'Fee Types',
        path: ROUTES.fees.feeTypes,
        permissionKeys: ['feetype'],
      },
      {
        id: 'fees-groups',
        label: 'Fee Groups',
        path: ROUTES.fees.feeGroups,
        permissionKeys: ['fees_group'],
      },
      {
        id: 'fees-assign',
        label: 'Assign Fees',
        path: ROUTES.fees.assign,
        permissionKeys: ['fees_group_assign'],
      },
      {
        id: 'fees-discounts',
        label: 'Fee Discounts',
        path: ROUTES.fees.discounts,
        permissionKeys: ['fees_discount'],
      },
      {
        id: 'fees-discounts-assign',
        label: 'Assign Discounts',
        path: ROUTES.fees.discountsAssign,
        permissionKeys: ['fees_discount'],
      },
      {
        id: 'fees-carry-forward',
        label: 'Carry Forward',
        path: ROUTES.fees.carryForward,
        permissionKeys: ['fees_forward'],
      },
      {
        id: 'fees-reminders',
        label: 'Fee Reminders',
        path: ROUTES.fees.reminders,
        permissionKeys: ['fees_reminder'],
      },
      {
        id: 'fees-offline',
        label: 'Offline Bank Payments',
        path: ROUTES.fees.offlinePayments,
        permissionKeys: ['offline_bank_payments'],
      },
      {
        id: 'fees-payment-gateways',
        label: 'Payment Gateways',
        path: ROUTES.fees.paymentGateways,
        permissionKeys: ['offline_bank_payments'],
      },
      {
        id: 'fees-scheme-scholarship',
        label: 'Scheme & Scholarship',
        path: ROUTES.fees.schemeScholarship,
        permissionKeys: ['fees_master'],
      },
      {
        id: 'fees-apply-scheme-scholarship',
        label: 'Apply Scheme & Scholarship',
        path: ROUTES.fees.applySchemeScholarship,
        permissionKeys: ['fees_master'],
      },
      {
        id: 'fees-positive-fee-adjustment',
        label: 'Positive Fee Adjustment',
        path: ROUTES.fees.positiveFeeAdjustment,
        permissionKeys: ['fees_master'],
      },
    ],
  },
  {
    id: 'examinations',
    label: 'Examinations',
    path: ROUTES.examinations.root,
    icon: BookOpen,
    section: 'operations',
    permissionKeys: ['exam_group', 'exam_schedule', 'exam_result'],
    children: [
      {
        id: 'exams-groups',
        label: 'Exam Groups',
        path: ROUTES.examinations.groups,
        permissionKeys: ['exam_group'],
      },
      {
        id: 'exams-list',
        label: 'Exams',
        path: ROUTES.examinations.exams,
        permissionKeys: ['exam_group'],
      },
      {
        id: 'exams-enroll',
        label: 'Enroll Students',
        path: ROUTES.examinations.enroll,
        permissionKeys: ['exam_group'],
      },
      {
        id: 'exams-schedule',
        label: 'Exam Schedule',
        path: ROUTES.examinations.schedule,
        permissionKeys: ['exam_schedule'],
      },
      {
        id: 'exams-results',
        label: 'Exam Results',
        path: ROUTES.examinations.results,
        permissionKeys: ['exam_result'],
      },
      {
        id: 'exams-admit-card',
        label: 'Admit Card',
        path: ROUTES.examinations.admitCard,
        permissionKeys: ['design_admit_card'],
      },
      {
        id: 'exams-print-admit-card',
        label: 'Print Admit Card',
        path: ROUTES.examinations.admitCard,
        comingSoon: true,
        permissionKeys: ['print_admit_card'],
      },
      {
        id: 'exams-marksheet',
        label: 'Marksheet',
        path: ROUTES.examinations.marksheet,
        permissionKeys: ['design_marksheet'],
      },
      {
        id: 'exams-print-marksheet',
        label: 'Print Marksheet',
        path: ROUTES.examinations.marksheet,
        comingSoon: true,
        permissionKeys: ['print_marksheet'],
      },
      {
        id: 'exams-grades',
        label: 'Marks Grade',
        path: ROUTES.examinations.grades,
        permissionKeys: ['marks_grade'],
      },
      {
        id: 'exams-divisions',
        label: 'Marks Division',
        path: ROUTES.examinations.divisions,
        permissionKeys: ['marks_division'],
      },
      {
        id: 'exams-cbse',
        label: 'CBSE Exams',
        path: ROUTES.examinations.cbseExams,
        permissionKeys: ['cbse_exam', 'exam_group'],
      },
      {
        id: 'exams-cbse-marks',
        label: 'CBSE Marks',
        path: ROUTES.examinations.cbseMarks,
        permissionKeys: ['cbse_exam_marks', 'exam_result'],
      },
    ],
  },
  {
    id: 'front-office',
    label: 'Front Office',
    path: ROUTES.frontOffice.root,
    icon: Home,
    section: 'operations',
    permissionKeys: ['admission_enquiry', 'visitor_book'],
    children: [
      {
        id: 'fo-enquiry',
        label: 'Admission Enquiry',
        path: ROUTES.frontOffice.enquiry,
        permissionKeys: ['admission_enquiry'],
      },
      {
        id: 'fo-visitors',
        label: 'Visitor Book',
        path: ROUTES.frontOffice.visitors,
        permissionKeys: ['visitor_book'],
      },
      {
        id: 'fo-calls',
        label: 'Phone Call Log',
        path: ROUTES.frontOffice.phoneCalls,
        permissionKeys: ['phone_call_log'],
      },
      {
        id: 'fo-dispatch',
        label: 'Postal Dispatch',
        path: ROUTES.frontOffice.dispatch,
        permissionKeys: ['postal_dispatch'],
      },
      {
        id: 'fo-receive',
        label: 'Postal Receive',
        path: ROUTES.frontOffice.receive,
        permissionKeys: ['postal_receive'],
      },
      {
        id: 'fo-complaints',
        label: 'Complaints',
        path: ROUTES.frontOffice.complaints,
        permissionKeys: ['complaint'],
      },
      {
        id: 'fo-setup',
        label: 'Setup Front Office',
        path: ROUTES.frontOffice.setup,
        permissionKeys: ['setup_font_office'],
      },
    ],
  },
  {
    id: 'library',
    label: 'Library',
    path: ROUTES.library.root,
    icon: Library,
    section: 'operations',
    permissionKeys: ['books', 'issue_return'],
    children: [
      {
        id: 'library-books',
        label: 'Book List',
        path: ROUTES.library.books,
        permissionKeys: ['books'],
      },
      {
        id: 'library-issue',
        label: 'Issue & Return',
        path: ROUTES.library.issueReturn,
        permissionKeys: ['issue_return'],
      },
      {
        id: 'library-add-student',
        label: 'Add Student',
        path: ROUTES.library.issueReturn,
        permissionKeys: ['add_student'],
      },
      {
        id: 'library-add-staff-member',
        label: 'Add Staff Member',
        path: ROUTES.library.issueReturn,
        permissionKeys: ['add_staff_member'],
      },
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    path: ROUTES.transport.root,
    icon: Bus,
    section: 'operations',
    permissionKeys: ['transport_fees', 'routes'],
    children: [
      {
        id: 'transport-fees',
        label: 'Transport Fees',
        path: ROUTES.transport.fees,
        permissionKeys: ['transport_fees'],
      },
      {
        id: 'transport-pickup',
        label: 'Pickup Points',
        path: ROUTES.transport.pickupPoints,
        permissionKeys: ['pickup_point'],
      },
      {
        id: 'transport-routes',
        label: 'Routes',
        path: ROUTES.transport.routes,
        permissionKeys: ['routes'],
      },
      {
        id: 'transport-vehicles',
        label: 'Vehicles',
        path: ROUTES.transport.vehicles,
        permissionKeys: ['vehicle'],
      },
      {
        id: 'transport-assign',
        label: 'Assign Vehicle',
        path: ROUTES.transport.assignVehicle,
        permissionKeys: ['assign_vehicle'],
      },
      {
        id: 'transport-route-pickup',
        label: 'Route Pickup Points',
        path: ROUTES.transport.routePickupPoints,
        permissionKeys: ['route_pickup_point'],
      },
      {
        id: 'transport-student-fees',
        label: 'Student Transport Fees',
        path: ROUTES.transport.studentFees,
        permissionKeys: ['transport_fees'],
      },
    ],
  },
  {
    id: 'hostel',
    label: 'Hostel',
    path: ROUTES.hostel.root,
    icon: Building2,
    section: 'operations',
    permissionKeys: ['hostel_rooms', 'hostel'],
    children: [
      {
        id: 'hostel-rooms',
        label: 'Hostel Rooms',
        path: ROUTES.hostel.rooms,
        permissionKeys: ['hostel_rooms'],
      },
      {
        id: 'hostel-room-types',
        label: 'Room Types',
        path: ROUTES.hostel.roomTypes,
        permissionKeys: ['hostel_room_type'],
      },
      {
        id: 'hostel-buildings',
        label: 'Hostels',
        path: ROUTES.hostel.hostels,
        permissionKeys: ['hostel'],
      },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    path: ROUTES.inventory.root,
    icon: Package,
    section: 'operations',
    permissionKeys: ['item', 'item_stock'],
    children: [
      {
        id: 'inventory-issue',
        label: 'Issue Item',
        path: ROUTES.inventory.issue,
        permissionKeys: ['issue_item'],
      },
      {
        id: 'inventory-stock',
        label: 'Add Item Stock',
        path: ROUTES.inventory.stock,
        permissionKeys: ['item_stock'],
      },
      {
        id: 'inventory-items',
        label: 'Items',
        path: ROUTES.inventory.items,
        permissionKeys: ['item'],
      },
      {
        id: 'inventory-categories',
        label: 'Item Categories',
        path: ROUTES.inventory.categories,
        permissionKeys: ['item_category'],
      },
      {
        id: 'inventory-stores',
        label: 'Item Stores',
        path: ROUTES.inventory.stores,
        permissionKeys: ['store'],
      },
      {
        id: 'inventory-suppliers',
        label: 'Suppliers',
        path: ROUTES.inventory.suppliers,
        permissionKeys: ['supplier'],
      },
    ],
  },
  {
    id: 'homework',
    label: 'Homework',
    path: ROUTES.homework.root,
    icon: ClipboardList,
    section: 'operations',
    permissionKeys: ['homework', 'daily_assignment'],
    children: [
      {
        id: 'homework-assignments',
        label: 'Homework',
        path: ROUTES.homework.assignments,
        permissionKeys: ['homework'],
      },
      {
        id: 'homework-daily',
        label: 'Daily Assignment',
        path: ROUTES.homework.daily,
        permissionKeys: ['daily_assignment'],
      },
    ],
  },
  {
    id: 'communicate',
    label: 'Communicate',
    path: ROUTES.communicate.root,
    icon: Mail,
    section: 'operations',
    permissionKeys: [
      'notice_board',
      'email',
      'sms',
      'login_credentials_send',
      'email_sms_log',
      'schedule_email_sms_log',
      'email_template',
      'sms_template',
    ],
    children: [
      {
        id: 'communicate-notices',
        label: 'Notice Board',
        path: ROUTES.communicate.notices,
        permissionKeys: ['notice_board'],
      },
      {
        id: 'communicate-send-email',
        label: 'Send Email',
        path: ROUTES.communicate.sendEmail,
        permissionKeys: ['email'],
      },
      {
        id: 'communicate-send-sms',
        label: 'Send SMS',
        path: ROUTES.communicate.sendSms,
        permissionKeys: ['sms'],
      },
      {
        id: 'communicate-email-sms',
        label: 'Send Email / SMS',
        path: ROUTES.communicate.emailSms,
        permissionKeys: ['email', 'sms'],
      },
      {
        id: 'communicate-email-sms-log',
        label: 'Email / SMS Log',
        path: ROUTES.communicate.emailSmsLog,
        permissionKeys: ['email_sms_log'],
      },
      {
        id: 'communicate-schedule-log',
        label: 'Schedule Email / SMS Log',
        path: ROUTES.communicate.scheduleLog,
        permissionKeys: ['schedule_email_sms_log'],
      },
      {
        id: 'communicate-bulk',
        label: 'Send Login Credentials',
        path: ROUTES.communicate.bulkEmail,
        permissionKeys: ['login_credentials_send'],
      },
      {
        id: 'communicate-email-template',
        label: 'Email Template',
        path: ROUTES.communicate.emailTemplate,
        permissionKeys: ['email_template'],
      },
      {
        id: 'communicate-sms-template',
        label: 'SMS Template',
        path: ROUTES.communicate.smsTemplate,
        permissionKeys: ['sms_template'],
      },
    ],
  },
  {
    id: 'download-center',
    label: 'Download Center',
    path: ROUTES.downloadCenter.root,
    icon: Download,
    section: 'operations',
    permissionKeys: ['upload_content', 'video_tutorial', 'content_type'],
    children: [
      {
        id: 'download-types',
        label: 'Content Types',
        path: ROUTES.downloadCenter.contentTypes,
        permissionKeys: ['content_type'],
      },
      {
        id: 'download-content',
        label: 'Upload Content',
        path: ROUTES.downloadCenter.content,
        permissionKeys: ['upload_content'],
      },
      {
        id: 'download-videos',
        label: 'Video Tutorials',
        path: ROUTES.downloadCenter.videos,
        permissionKeys: ['video_tutorial'],
      },
      {
        id: 'download-share-content',
        label: 'Share Content',
        path: ROUTES.downloadCenter.shareContent,
        permissionKeys: ['content_share_list'],
      },
    ],
  },
  {
    id: 'lesson-plan',
    label: 'Lesson Plan',
    path: ROUTES.lessonPlan.root,
    icon: FileText,
    section: 'operations',
    permissionKeys: [
      'manage_lesson_plan',
      'manage_syllabus_status',
      'lesson',
      'topic',
      'copy_old_lesson',
    ],
    children: [
      {
        id: 'lesson-manage-lesson-plan',
        label: 'Manage Lesson Plan',
        path: ROUTES.lessonPlan.manage,
        permissionKeys: ['manage_lesson_plan'],
      },
      {
        id: 'lesson-syllabus',
        label: 'Syllabus Status',
        path: ROUTES.lessonPlan.syllabusStatus,
        permissionKeys: ['manage_syllabus_status'],
      },
      {
        id: 'lesson-lessons',
        label: 'Lessons',
        path: ROUTES.lessonPlan.lessons,
        permissionKeys: ['lesson'],
      },
      {
        id: 'lesson-topics',
        label: 'Topics',
        path: ROUTES.lessonPlan.topics,
        permissionKeys: ['topic'],
      },
      {
        id: 'lesson-copy-old-lessons',
        label: 'Copy Old Lessons',
        path: ROUTES.lessonPlan.copy,
        permissionKeys: ['copy_old_lesson'],
      },
    ],
  },
  {
    id: 'online-exams',
    label: 'Online Examinations',
    path: ROUTES.onlineExams.root,
    icon: Target,
    section: 'operations',
    permissionKeys: ['online_examination', 'question_bank'],
    children: [
      {
        id: 'online-exams-setup',
        label: 'Online Exam',
        path: ROUTES.onlineExams.exams,
        permissionKeys: ['online_examination'],
      },
      {
        id: 'online-exams-questions',
        label: 'Question Bank',
        path: ROUTES.onlineExams.questionBank,
        permissionKeys: ['question_bank'],
      },
    ],
  },
  {
    id: 'income',
    label: 'Income',
    path: ROUTES.income.root,
    icon: Wallet,
    section: 'finance',
    permissionKeys: ['income', 'income_head'],
    children: [
      {
        id: 'income-list',
        label: 'Add Income',
        path: ROUTES.income.list,
        permissionKeys: ['income'],
      },
      {
        id: 'income-search',
        label: 'Search Income',
        path: ROUTES.income.search,
        permissionKeys: ['income'],
      },
      {
        id: 'income-heads',
        label: 'Income Heads',
        path: ROUTES.income.heads,
        permissionKeys: ['income_head'],
      },
    ],
  },
  {
    id: 'expense',
    label: 'Expense',
    path: ROUTES.expense.root,
    icon: Receipt,
    section: 'finance',
    permissionKeys: ['expense', 'expense_head'],
    children: [
      {
        id: 'expense-list',
        label: 'Add Expense',
        path: ROUTES.expense.list,
        permissionKeys: ['expense'],
      },
      {
        id: 'expense-search',
        label: 'Search Expense',
        path: ROUTES.expense.search,
        permissionKeys: ['expense'],
      },
      {
        id: 'expense-heads',
        label: 'Expense Heads',
        path: ROUTES.expense.heads,
        permissionKeys: ['expense_head'],
      },
    ],
  },
  {
    id: 'finance',
    label: 'Account Finance',
    path: ROUTES.finance.root,
    icon: Landmark,
    section: 'finance',
    permissionKeys: ['accounts', 'entries'],
    children: [
      {
        id: 'finance-coa',
        label: 'Chart of Accounts',
        path: ROUTES.finance.chartOfAccounts,
        permissionKeys: ['accounts'],
      },
      {
        id: 'finance-mapper',
        label: 'Account Mapper',
        path: ROUTES.finance.mapper,
        permissionKeys: ['accounts'],
      },
      {
        id: 'finance-entries',
        label: 'Journal Entries',
        path: ROUTES.finance.entries,
        permissionKeys: ['entries'],
      },
      {
        id: 'finance-groups',
        label: 'Ledger Groups',
        path: ROUTES.finance.groups,
        permissionKeys: ['accounts'],
      },
      {
        id: 'finance-ledgers',
        label: 'Ledgers',
        path: ROUTES.finance.ledgers,
        permissionKeys: ['accounts'],
      },
    ],
  },
  {
    id: 'finance-reports',
    label: 'Financial Reports',
    path: ROUTES.finance.reports,
    icon: FileBarChart,
    section: 'finance',
    permissionKeys: ['trialbalance', 'balancesheet', 'profitloss', 'index'],
    children: [
      {
        id: 'finance-reports-dashboard',
        label: 'Dashboard',
        path: ROUTES.finance.reports,
        permissionKeys: ['index', 'trialbalance', 'balancesheet', 'profitloss'],
      },
      {
        id: 'finance-trial-balance',
        label: 'Trial Balance',
        path: ROUTES.finance.trialBalance,
        permissionKeys: ['trialbalance'],
      },
      {
        id: 'finance-balance-sheet',
        label: 'Balance Sheet',
        path: ROUTES.finance.balanceSheet,
        permissionKeys: ['balancesheet'],
      },
      {
        id: 'finance-profit-loss',
        label: 'Profit & Loss',
        path: ROUTES.finance.profitLoss,
        permissionKeys: ['profitloss'],
      },
      {
        id: 'finance-ledger-statement',
        label: 'Ledger Statement',
        path: ROUTES.finance.ledgerStatement,
        permissionKeys: ['index'],
      },
      {
        id: 'finance-ledger-entries',
        label: 'Ledger Entries',
        path: ROUTES.finance.ledgerEntries,
        permissionKeys: ['index'],
      },
      {
        id: 'finance-reconciliation',
        label: 'Reconciliation',
        path: ROUTES.finance.reconciliation,
        permissionKeys: ['index'],
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    path: ROUTES.reports.root,
    icon: BarChart3,
    section: 'insights',
    permissionKeys: [
      'student_report',
      'attendance_report',
      'finance_report',
      'alumni_report',
      'syllabus_status_report',
      'user_log',
      'audit_trail_report',
      'online_exams_report',
    ],
    children: [
      {
        id: 'reports-students',
        label: 'Student Reports',
        path: ROUTES.reports.students,
        permissionKeys: ['student_report'],
      },
      {
        id: 'reports-attendance',
        label: 'Attendance Reports',
        path: ROUTES.reports.attendance,
        permissionKeys: ['attendance_report'],
      },
      {
        id: 'reports-fees',
        label: 'Finance & Fees',
        path: ROUTES.reports.fees,
        permissionKeys: ['finance_report'],
      },
      {
        id: 'reports-exams',
        label: 'Exam Reports',
        path: ROUTES.reports.examinations,
        permissionKeys: ['exam_result_report'],
      },
      {
        id: 'reports-finance',
        label: 'Income & Expense',
        path: ROUTES.reports.finance,
        permissionKeys: ['finance_report'],
      },
      {
        id: 'reports-library',
        label: 'Library Reports',
        path: ROUTES.reports.library,
        permissionKeys: [
          'book_issue_report',
          'book_due_report',
          'book_issue_return_report',
          'book_inventory_report',
        ],
      },
      {
        id: 'reports-inventory',
        label: 'Inventory Reports',
        path: ROUTES.reports.inventory,
        permissionKeys: ['stock_report', 'add_item_report', 'issue_item_report'],
      },
      {
        id: 'reports-hr',
        label: 'HR Reports',
        path: ROUTES.reports.hr,
        permissionKeys: ['staff_report'],
      },
      {
        id: 'reports-transport',
        label: 'Transport & Hostel',
        path: ROUTES.reports.transport,
        permissionKeys: ['transport_report', 'hostel_report'],
      },
      {
        id: 'reports-homework',
        label: 'Homework Reports',
        path: ROUTES.reports.homework,
        permissionKeys: ['homework', 'daily_assignment'],
      },
      {
        id: 'reports-alumni',
        label: 'Alumni Report',
        path: ROUTES.reports.alumni,
        permissionKeys: ['alumni_report'],
      },
      {
        id: 'reports-lesson-plan',
        label: 'Lesson Plan Reports',
        path: ROUTES.reports.lessonPlan,
        permissionKeys: ['syllabus_status_report', 'teacher_syllabus_status_report'],
      },
      {
        id: 'reports-user-log',
        label: 'User Log Reports',
        path: ROUTES.reports.userLog,
        permissionKeys: ['user_log'],
      },
      {
        id: 'reports-audit-trail',
        label: 'Audit Trail Reports',
        path: ROUTES.reports.auditTrail,
        permissionKeys: ['audit_trail_report'],
      },
      {
        id: 'reports-online-exams',
        label: 'Online Exam Reports',
        path: ROUTES.reports.onlineExams,
        permissionKeys: ['online_exams_report', 'online_exam_wise_report'],
      },
      {
        id: 'reports-timetable',
        label: 'Timetable Report',
        path: ROUTES.reports.timetable,
        permissionKeys: ['timetable_report'],
      },
    ],
  },
  {
    id: 'certificates',
    label: 'Certificates',
    path: ROUTES.certificates.root,
    icon: CreditCard,
    section: 'insights',
    permissionKeys: [
      'student_certificate',
      'generate_certificate',
      'student_id_card',
      'generate_id_card',
      'staff_id_card',
      'generate_staff_id_card',
    ],
    children: [
      {
        id: 'cert-templates',
        label: 'Certificate Templates',
        path: ROUTES.certificates.templates,
        permissionKeys: ['student_certificate'],
      },
      {
        id: 'cert-generate',
        label: 'Generate Certificate',
        path: ROUTES.certificates.generate,
        permissionKeys: ['generate_certificate'],
      },
      {
        id: 'cert-student-id',
        label: 'Student ID Card',
        path: ROUTES.certificates.studentIdCard,
        permissionKeys: ['student_id_card'],
      },
      {
        id: 'cert-generate-id',
        label: 'Generate ID Card',
        path: ROUTES.certificates.generateIdCard,
        permissionKeys: ['generate_id_card'],
      },
      {
        id: 'cert-staff-id',
        label: 'Staff ID Card',
        path: ROUTES.certificates.staffIdCard,
        permissionKeys: ['staff_id_card'],
      },
      {
        id: 'cert-generate-staff-id',
        label: 'Generate Staff ID',
        path: ROUTES.certificates.generateStaffIdCard,
        permissionKeys: ['generate_staff_id_card'],
      },
    ],
  },
  {
    id: 'alumni',
    label: 'Alumni',
    path: ROUTES.alumni.root,
    icon: Megaphone,
    section: 'insights',
    permissionKeys: ['manage_alumni', 'events'],
    children: [
      {
        id: 'alumni-list',
        label: 'Manage Alumni',
        path: ROUTES.alumni.list,
        permissionKeys: ['manage_alumni'],
      },
      {
        id: 'alumni-events',
        label: 'Alumni Events',
        path: ROUTES.alumni.events,
        permissionKeys: ['events'],
      },
    ],
  },
  {
    id: 'leads',
    label: 'Lead Management',
    path: ROUTES.leads.root,
    icon: UserPlus,
    section: 'insights',
    permissionKeys: ['lead_manager', 'all_leads', 'leads_follow_up'],
    children: [
      {
        id: 'leads-all',
        label: 'All Leads',
        path: ROUTES.leads.all,
        permissionKeys: ['all_leads'],
      },
      {
        id: 'leads-managed',
        label: 'Managed Leads',
        path: ROUTES.leads.managed,
        permissionKeys: ['managed_leads'],
      },
      {
        id: 'leads-unmanaged',
        label: 'Unmanaged Leads',
        path: ROUTES.leads.unmanaged,
        permissionKeys: ['unmanaged_leads'],
      },
      {
        id: 'leads-campaigns',
        label: 'Campaigns',
        path: ROUTES.leads.campaigns,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-campaign-types',
        label: 'Campaign Types',
        path: ROUTES.leads.campaignTypes,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-promoters',
        label: 'Promoters',
        path: ROUTES.leads.promoters,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-followup-status',
        label: 'Follow-up Status',
        path: ROUTES.leads.followUpStatus,
        permissionKeys: ['leads_follow_up'],
      },
      {
        id: 'leads-followups',
        label: 'Follow-ups',
        path: ROUTES.leads.followUps,
        permissionKeys: ['leads_follow_up'],
      },
      {
        id: 'leads-reports',
        label: 'Reports',
        path: ROUTES.leads.reports,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-promoter-commission-report',
        label: 'Promoter Commission Report',
        path: ROUTES.leads.promoterCommissionReport,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-brief-reports',
        label: 'Brief Reports',
        path: ROUTES.leads.briefReports,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-call-reports',
        label: 'Call Reports',
        path: ROUTES.leads.callReports,
        permissionKeys: ['lead_manager'],
      },
      {
        id: 'leads-travel-reports',
        label: 'Travel Reports',
        path: ROUTES.leads.travelReports,
        permissionKeys: ['lead_manager'],
      },
    ],
  },
  {
    id: 'cms',
    label: 'Front CMS',
    path: ROUTES.cms.root,
    icon: FileText,
    section: 'insights',
    permissionKeys: [
      'event',
      'gallery',
      'notice',
      'media_manager',
      'pages',
      'menus',
      'banner_images',
      'front_cms_setting',
    ],
    children: [
      { id: 'cms-events', label: 'Events', path: ROUTES.cms.events, permissionKeys: ['event'] },
      {
        id: 'cms-gallery',
        label: 'Gallery',
        path: ROUTES.cms.gallery,
        permissionKeys: ['gallery'],
      },
      { id: 'cms-notices', label: 'News', path: ROUTES.cms.notices, permissionKeys: ['notice'] },
      {
        id: 'cms-media',
        label: 'Media Manager',
        path: ROUTES.cms.media,
        permissionKeys: ['media_manager'],
      },
      { id: 'cms-pages', label: 'Pages', path: ROUTES.cms.pages, permissionKeys: ['pages'] },
      { id: 'cms-menus', label: 'Menus', path: ROUTES.cms.menus, permissionKeys: ['menus'] },
      {
        id: 'cms-banners',
        label: 'Banners',
        path: ROUTES.cms.banners,
        permissionKeys: ['banner_images'],
      },
      {
        id: 'cms-settings',
        label: 'CMS Settings',
        path: ROUTES.cms.settings,
        permissionKeys: ['front_cms_setting'],
      },
    ],
  },
  {
    id: 'lms',
    label: 'Online Courses',
    path: ROUTES.lms.courses.root,
    icon: Monitor,
    section: 'operations',
    permissionKeys: ['online_course'], // Or an appropriate permission
    children: [
      {
        id: 'lms-courses',
        label: 'Courses',
        path: ROUTES.lms.courses.root,
        permissionKeys: ['online_course'],
      },
      {
        id: 'lms-offline-payment',
        label: 'Offline Payment',
        comingSoon: true,
        permissionKeys: ['online_course_offline_payment'],
      },
      {
        id: 'lms-categories',
        label: 'Course Category',
        comingSoon: true,
        permissionKeys: ['course_category'],
      },
      {
        id: 'lms-reports',
        label: 'Online Course Report',
        comingSoon: true,
        permissionKeys: ['online_course_report'],
      },
      {
        id: 'lms-settings',
        label: 'Settings',
        comingSoon: true,
        permissionKeys: ['online_course_setting'],
      },
    ],
  },
  {
    id: 'gmeet',
    label: 'GMeet Live Classes',
    icon: Monitor,
    section: 'operations',
    permissionKeys: ['live_classes'],
    comingSoon: true,
    children: [
      { id: 'gmeet-classes', label: 'Live Classes', comingSoon: true },
      { id: 'gmeet-meeting', label: 'Live Meeting', comingSoon: true },
      { id: 'gmeet-report', label: 'Class Report', comingSoon: true },
      { id: 'gmeet-setting', label: 'GMeet Setting', comingSoon: true },
    ],
  },
  {
    id: 'zoom',
    label: 'Zoom Live Classes',
    icon: Monitor,
    section: 'operations',
    permissionKeys: ['zoom_live_classes'],
    comingSoon: true,
    children: [
      { id: 'zoom-meeting', label: 'Live Meeting', comingSoon: true },
      { id: 'zoom-class', label: 'Live Class', comingSoon: true },
      { id: 'zoom-class-report', label: 'Class Report', comingSoon: true },
      { id: 'zoom-meeting-report', label: 'Meeting Report', comingSoon: true },
      { id: 'zoom-setting', label: 'Settings', comingSoon: true },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    path: ROUTES.settings.root,
    icon: Settings,
    section: 'system',
    permissionKeys: ['general_setting', 'roles'],
    children: [
      {
        id: 'settings-general',
        label: 'General Settings',
        path: ROUTES.settings.general,
        permissionKeys: ['general_setting'],
      },
      {
        id: 'settings-languages',
        label: 'Languages',
        path: ROUTES.settings.languages,
        permissionKeys: ['languages'],
      },
      {
        id: 'settings-currency',
        label: 'Currency',
        path: ROUTES.settings.currency,
        permissionKeys: ['currency'],
      },
      {
        id: 'settings-notifications',
        label: 'Notifications',
        path: ROUTES.settings.notifications,
        permissionKeys: ['notification_setting'],
      },
      {
        id: 'settings-sms',
        label: 'SMS Config',
        path: ROUTES.settings.sms,
        permissionKeys: ['sms_setting'],
      },
      {
        id: 'settings-email',
        label: 'Email Config',
        path: ROUTES.settings.email,
        permissionKeys: ['email_setting'],
      },
      {
        id: 'settings-payment',
        label: 'Payment Methods',
        path: ROUTES.settings.paymentMethods,
        permissionKeys: ['payment_methods'],
      },
      {
        id: 'settings-print',
        label: 'Print Header & Footer',
        path: ROUTES.settings.printHeaderFooter,
        permissionKeys: ['print_header_footer'],
      },
      {
        id: 'settings-roles',
        label: 'Roles & Permissions',
        path: ROUTES.settings.roles,
        permissionKeys: ['roles'],
      },
      {
        id: 'settings-users',
        label: 'User Accounts',
        path: ROUTES.settings.users,
        permissionKeys: ['user_status'],
      },
      {
        id: 'settings-modules',
        label: 'Modules',
        path: ROUTES.settings.modules,
        permissionKeys: ['superadmin'],
      },
      {
        id: 'settings-custom-fields',
        label: 'Custom Fields',
        path: ROUTES.settings.customFields,
        permissionKeys: ['custom_fields'],
      },
      {
        id: 'settings-captcha',
        label: 'Captcha',
        path: ROUTES.settings.captcha,
        permissionKeys: ['captcha_setting'],
      },
      {
        id: 'settings-system-fields',
        label: 'System Fields',
        path: ROUTES.settings.systemFields,
        permissionKeys: ['system_fields'],
      },
      {
        id: 'settings-online-admission',
        label: 'Online Admission',
        path: ROUTES.settings.onlineAdmission,
        permissionKeys: ['online_admission'],
      },
      {
        id: 'settings-sidebar',
        label: 'Sidebar Menu',
        path: ROUTES.settings.sidebarMenu,
        permissionKeys: ['sidebar_menu'],
      },
      {
        id: 'settings-backup',
        label: 'Backup / Restore',
        path: ROUTES.settings.backup,
        permissionKeys: ['backup'],
      },
      {
        id: 'settings-file-types',
        label: 'File Types',
        path: ROUTES.settings.fileTypes,
        permissionKeys: ['superadmin'],
      },
    ],
  },
];
