import type { NavPermissionKey } from '@app-types/navigation';
import type { Permission } from '@app-types/permissions';

/**
 * Maps modern UI permission keys to legacy permission_category keys.
 * Replace this map when backend exposes permissions directly from `/me`.
 */
export const PERMISSION_TO_LEGACY: Partial<Record<Permission, NavPermissionKey[]>> = {
  'students.view': ['student', 'student_report'],
  'students.create': ['student', 'import_student'],
  'students.delete': ['student', 'disable_student'],
  'students.categories.create': ['student_categories'],
  'students.categories.edit': ['student_categories'],
  'students.categories.delete': ['student_categories'],
  'students.houses.create': ['student_houses'],
  'students.houses.edit': ['student_houses'],
  'students.houses.delete': ['student_houses'],
  'students.import.view': ['import_student'],
  'staff.view': ['staff', 'staff_report'],
  'staff.create': ['staff'],
  'staff.edit': ['staff'],
  'staff.delete': ['staff'],
  'staff.departments.create': ['department'],
  'staff.departments.edit': ['department'],
  'staff.departments.delete': ['department'],
  'staff.designations.create': ['designation'],
  'staff.designations.edit': ['designation'],
  'staff.designations.delete': ['designation'],
  'staff.attendance.mark': ['staff_attendance'],
  'staff.payroll.create': ['staff_payroll'],
  'staff.payroll.edit': ['staff_payroll'],
  'staff.payroll.delete': ['staff_payroll'],
  'settings.manage': [
    'general_setting',
    'session_setting',
    'languages',
    'currency',
    'roles',
    'user_status',
  ],
  'general_settings.view': ['general_setting'],
  'general_settings.edit': ['general_setting'],
  'academics.manage': [
    'class',
    'section',
    'subject',
    'subject_group',
    'class_timetable',
    'teachers_time_table',
    'assign_class_teacher',
    'promote_student',
    'session_setting',
  ],
  'classes.view': ['class'],
  'classes.create': ['class'],
  'classes.edit': ['class'],
  'classes.delete': ['class'],
  'sections.view': ['section'],
  'sections.create': ['section'],
  'sections.edit': ['section'],
  'sections.delete': ['section'],
  'subjects.view': ['subject'],
  'subjects.create': ['subject'],
  'subjects.edit': ['subject'],
  'subjects.delete': ['subject'],
  'subject_groups.view': ['subject_group'],
  'subject_groups.create': ['subject_group'],
  'subject_groups.edit': ['subject_group'],
  'subject_groups.delete': ['subject_group'],
  'timetable.view': ['class_timetable'],
  'timetable.create': ['class_timetable'],
  'timetable.edit': ['class_timetable'],
  'timetable.delete': ['class_timetable'],
  'teacher_timetable.view': ['teachers_time_table'],
  'class_teacher.view': ['assign_class_teacher'],
  'class_teacher.create': ['assign_class_teacher'],
  'class_teacher.edit': ['assign_class_teacher'],
  'class_teacher.delete': ['assign_class_teacher'],
  'promote_students.view': ['promote_student'],
  'promote_students.create': ['promote_student'],
  'sessions.view': ['session_setting'],
  'sessions.create': ['session_setting'],
  'sessions.edit': ['session_setting'],
  'sessions.delete': ['session_setting'],
  'fees.manage': [
    'collect_fees',
    'fees_master',
    'feetype',
    'fees_group',
    'fees_discount',
    'fees_forward',
    'search_due_fees',
    'search_fees_payment',
    'offline_bank_payments',
  ],
  'fees.student_assign': ['fees_group_assign'],
  'fees.carry_forward': ['fees_forward'],
  'attendance.mark': ['student_attendance', 'subject_attendance'],
  'attendance.report': ['student_attendance', 'attendance_report'],
  'exams.view': ['exam_group', 'exam_schedule', 'exam_result'],
  'exams.create': ['exam_group', 'exam_schedule', 'exam_result'],
  'exams.edit': ['exam_group', 'exam_schedule', 'exam_result'],
  'exams.delete': ['exam_group', 'exam_schedule'],
  'exams.submit': ['exam_result'],
  'exams.approve': ['exam_result'],
  'exams.admit_card.create': ['design_admit_card'],
  'exams.admit_card.edit': ['design_admit_card'],
  'exams.admit_card.delete': ['design_admit_card'],
  'exams.marksheet.create': ['design_marksheet'],
  'exams.marksheet.edit': ['design_marksheet'],
  'exams.marksheet.delete': ['design_marksheet'],
  'front_office.phone_calls.create': ['phone_call_log'],
  'front_office.phone_calls.edit': ['phone_call_log'],
  'front_office.phone_calls.delete': ['phone_call_log'],
  'front_office.visitor_purpose.create': ['setup_font_office'],
  'front_office.visitor_purpose.edit': ['setup_font_office'],
  'front_office.visitor_purpose.delete': ['setup_font_office'],
  'notifications.view': ['notice_board', 'email', 'sms', 'login_credentials_send'],
  'communicate.email.send': ['email'],
  'communicate.sms.send': ['sms'],
  'communicate.bulk_email.send': ['login_credentials_send'],
  'communicate.messages.view': ['email_sms_log', 'email', 'sms'],
  'transport.create': [
    'routes',
    'transport_fees_master',
    'pickup_point',
    'route_pickup_point',
    'vehicle',
    'assign_vehicle',
  ],
  'transport.edit': [
    'routes',
    'transport_fees_master',
    'pickup_point',
    'route_pickup_point',
    'vehicle',
    'assign_vehicle',
  ],
  'transport.delete': [
    'routes',
    'transport_fees_master',
    'pickup_point',
    'route_pickup_point',
    'vehicle',
    'assign_vehicle',
  ],
  'manage_syllabus_status.view': ['manage_syllabus_status'],
  'manage_syllabus_status.create': ['manage_syllabus_status'],
  'manage_syllabus_status.edit': ['manage_syllabus_status'],
  'manage_syllabus_status.delete': ['manage_syllabus_status'],
  'manage_lesson.view': ['lesson_plan', 'manage_lesson'],
  'manage_lesson.create': ['lesson_plan', 'manage_lesson'],
  'manage_lesson.edit': ['lesson_plan', 'manage_lesson'],
  'manage_lesson.delete': ['lesson_plan', 'manage_lesson'],
  'manage_topic.view': ['lesson_plan', 'manage_topic'],
  'manage_topic.create': ['lesson_plan', 'manage_topic'],
  'manage_topic.edit': ['lesson_plan', 'manage_topic'],
  'manage_topic.delete': ['lesson_plan', 'manage_topic'],
  'homework.view': ['homework'],
  'homework.create': ['homework'],
  'homework.edit': ['homework'],
  'homework.delete': ['homework'],
  'daily_assignment.view': ['daily_assignment'],
  'daily_assignment.create': ['daily_assignment'],
  'daily_assignment.edit': ['daily_assignment'],
  'daily_assignment.delete': ['daily_assignment'],
  'finance.entries.view': ['entries'],
  'finance.entries.create': ['entries'],
  'finance.entries.delete': ['entries'],
  'finance.accounts.manage': ['accounts'],
  'finance.reports.index': ['index'],
  'finance.reports.trialbalance': ['trialbalance'],
  'finance.reports.balancesheet': ['balancesheet'],
  'finance.reports.profitloss': ['profitloss'],
  'alumni.manage.create': ['manage_alumni'],
  'alumni.manage.edit': ['manage_alumni'],
  'alumni.manage.delete': ['manage_alumni'],
  'alumni.events.create': ['events'],
  'alumni.events.edit': ['events'],
  'alumni.events.delete': ['events'],
  'reports.alumni.view': ['alumni_report'],
  'library.books.view': ['books'],
  'library.books.create': ['books'],
  'library.books.edit': ['books'],
  'library.books.delete': ['books'],
  'library.issue.view': ['issue_return'],
  'inventory.category.create': ['item_category'],
  'inventory.category.edit': ['item_category'],
  'inventory.category.delete': ['item_category'],
  'inventory.store.create': ['store'],
  'inventory.store.edit': ['store'],
  'inventory.store.delete': ['store'],
  'inventory.supplier.create': ['supplier'],
  'inventory.supplier.edit': ['supplier'],
  'inventory.supplier.delete': ['supplier'],
  'inventory.item.create': ['item'],
  'inventory.item.edit': ['item'],
  'inventory.item.delete': ['item'],
  'inventory.stock.create': ['item_stock'],
  'inventory.stock.delete': ['item_stock'],
  'inventory.issue.create': ['issue_item'],
  'inventory.issue.edit': ['issue_item'],
  'income.create': ['income'],
  'income.edit': ['income'],
  'income.delete': ['income'],
  'income.head.create': ['income_head'],
  'income.head.edit': ['income_head'],
  'income.head.delete': ['income_head'],
  'expense.create': ['expense'],
  'expense.edit': ['expense'],
  'expense.delete': ['expense'],
  'expense.head.create': ['expense_head'],
  'expense.head.edit': ['expense_head'],
  'expense.head.delete': ['expense_head'],
  'certificates.template.create': ['student_certificate'],
  'certificates.template.edit': ['student_certificate'],
  'certificates.template.delete': ['student_certificate'],
  'certificates.generate.view': ['generate_certificate'],
  'idcards.student.create': ['student_id_card'],
  'idcards.student.edit': ['student_id_card'],
  'idcards.student.delete': ['student_id_card'],
  'idcards.student.generate': ['generate_id_card'],
  'idcards.staff.create': ['staff_id_card'],
  'idcards.staff.edit': ['staff_id_card'],
  'idcards.staff.delete': ['staff_id_card'],
  'idcards.staff.generate': ['generate_staff_id_card'],
  'downloadcenter.type.create': ['content_type'],
  'downloadcenter.type.edit': ['content_type'],
  'downloadcenter.type.delete': ['content_type'],
  'downloadcenter.content.create': ['upload_content'],
  'downloadcenter.content.delete': ['upload_content'],
  'downloadcenter.video.create': ['video_tutorial'],
  'downloadcenter.video.edit': ['video_tutorial'],
  'downloadcenter.video.delete': ['video_tutorial'],
  'onlineexams.exam.create': ['online_examination'],
  'onlineexams.exam.edit': ['online_examination'],
  'onlineexams.exam.delete': ['online_examination'],
  'onlineexams.question.create': ['question_bank'],
  'onlineexams.question.edit': ['question_bank'],
  'onlineexams.question.delete': ['question_bank'],
  'onlineexams.exam.questions': ['add_questions_in_exam'],
  'onlineexams.exam.assign': ['online_assign_view_student'],
};

export interface NavigationPermissionContext {
  /** Legacy permission_category keys from backend (future: from auth store). */
  legacyKeys: ReadonlySet<NavPermissionKey>;
  /** Modern UI permission keys (current static role map). */
  uiKeys: ReadonlySet<Permission>;
}

export interface NavigationPermissionChecker {
  canAccessNavItem(permissionKeys?: NavPermissionKey[], requireAll?: boolean): boolean;
}

export function createNavigationPermissionChecker(
  context: NavigationPermissionContext,
): NavigationPermissionChecker {
  const expandedUiLegacyKeys = new Set<NavPermissionKey>(context.legacyKeys);

  for (const uiKey of context.uiKeys) {
    const mapped = PERMISSION_TO_LEGACY[uiKey];
    mapped?.forEach((key) => expandedUiLegacyKeys.add(key));
  }

  return {
    canAccessNavItem(permissionKeys, requireAll = false) {
      if (!permissionKeys?.length) return true;

      if (requireAll) {
        return permissionKeys.every((key) => expandedUiLegacyKeys.has(key));
      }

      return permissionKeys.some((key) => expandedUiLegacyKeys.has(key));
    },
  };
}

/** Superadmin bypass — all navigation visible until backend wiring is complete. */
export function createPermissiveChecker(): NavigationPermissionChecker {
  return {
    canAccessNavItem() {
      return true;
    },
  };
}
