# Generated by Django 5.1.15 on 2026-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_field",
                    models.CharField(
                        blank=True, db_column="class", max_length=60, null=True
                    ),
                ),
                ("sort_order", models.IntegerField(default=9999)),
                (
                    "is_hedu_program",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "classes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClassSections",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "section_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "class_sections",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClassSectionTimes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_section_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "class_section_times",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClassTeacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.IntegerField(db_index=True)),
                ("class_id", models.IntegerField(db_index=True)),
                ("section_id", models.IntegerField(db_index=True)),
                ("staff_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": "class_teacher",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DailyAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_session_id", models.IntegerField(db_index=True)),
                ("subject_group_subject_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("attachment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "evaluated_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("evaluation_date", models.DateField(blank=True, null=True)),
                ("remark", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "daily_assignment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_id", models.IntegerField(db_index=True)),
                ("section_id", models.IntegerField(db_index=True)),
                ("session_id", models.IntegerField(db_index=True)),
                ("staff_id", models.IntegerField(db_index=True)),
                (
                    "subject_group_subject_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subject_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("homework_date", models.DateField()),
                ("submit_date", models.DateField()),
                ("marks", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("assigned_to_house", models.IntegerField(blank=True, null=True)),
                ("assigned_to_president", models.IntegerField(blank=True, null=True)),
                ("create_date", models.DateField()),
                ("evaluation_date", models.DateField(blank=True, null=True)),
                ("document", models.CharField(blank=True, max_length=200, null=True)),
                ("created_by", models.IntegerField(db_index=True)),
                (
                    "evaluated_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "homework",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HomeworkEvaluation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("homework_id", models.IntegerField(db_index=True)),
                ("student_id", models.IntegerField(db_index=True)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("marks", models.FloatField(blank=True, null=True)),
                ("note", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "homework_evaluation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.IntegerField(db_index=True)),
                ("subject_group_subject_id", models.IntegerField(db_index=True)),
                ("subject_group_class_sections_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "lesson",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LessonPlanForum",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_syllabus_id", models.IntegerField(db_index=True)),
                ("type", models.CharField(max_length=20)),
                ("staff_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "student_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lesson_plan_forum",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sections",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("section", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "sections",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectGroupClassSections",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subject_group_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "class_section_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "subject_group_class_sections",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectGroups",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("parent_subject_group_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "subject_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectGroups1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("parent_subject_group_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "subject_groups1",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectGroupSubjects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subject_group_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subject_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "subject_group_subjects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("linked_class", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "subjects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectSyllabus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic_id", models.IntegerField(db_index=True)),
                ("session_id", models.IntegerField(db_index=True)),
                ("created_by", models.IntegerField(db_index=True)),
                ("created_for", models.IntegerField(db_index=True)),
                ("date", models.DateField()),
                ("time_from", models.CharField(max_length=255)),
                ("time_to", models.CharField(max_length=255)),
                ("presentation", models.TextField()),
                ("attachment", models.TextField()),
                ("lacture_youtube_url", models.CharField(max_length=255)),
                ("lacture_video", models.CharField(max_length=255)),
                ("sub_topic", models.TextField()),
                ("teaching_method", models.TextField()),
                ("general_objectives", models.TextField()),
                ("previous_knowledge", models.TextField()),
                ("comprehensive_questions", models.TextField()),
                ("status", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "subject_syllabus",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectTimetable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("class_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "section_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subject_group_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subject_group_subject_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("staff_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("day", models.CharField(blank=True, max_length=20, null=True)),
                ("time_from", models.CharField(blank=True, max_length=20, null=True)),
                ("time_to", models.CharField(blank=True, max_length=20, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("room_no", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "subject_timetable",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubmitAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("homework_id", models.IntegerField(db_index=True)),
                ("student_id", models.IntegerField(db_index=True)),
                ("message", models.TextField()),
                ("docs", models.CharField(max_length=225)),
                ("file_name", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "submit_assignment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.IntegerField(db_index=True)),
                ("lesson_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("status", models.IntegerField()),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "topic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VideoTutorial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("vid_title", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("thumb_path", models.CharField(blank=True, max_length=500, null=True)),
                ("dir_path", models.CharField(blank=True, max_length=500, null=True)),
                ("img_name", models.CharField(max_length=300)),
                ("thumb_name", models.CharField(max_length=300)),
                ("video_link", models.CharField(max_length=100)),
                ("created_by", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "video_tutorial",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VideoTutorialClassSections",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("video_tutorial_id", models.IntegerField(db_index=True)),
                ("class_section_id", models.IntegerField(db_index=True)),
                ("created_date", models.DateField()),
            ],
            options={
                "db_table": "video_tutorial_class_sections",
                "managed": False,
            },
        ),
    ]
