# Generated by Django 5.1.15 on 2026-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisableReason",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "disable_reason",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentApplyleave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_session_id", models.IntegerField(db_index=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("apply_date", models.DateField()),
                ("status", models.IntegerField()),
                ("docs", models.CharField(blank=True, max_length=200, null=True)),
                ("reason", models.TextField()),
                (
                    "approve_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("approve_date", models.DateField(blank=True, null=True)),
                ("request_type", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_applyleave",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentAttendences",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("biometric_attendence", models.IntegerField(default=0)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "attendence_type_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("remark", models.CharField(max_length=200)),
                ("biometric_device_data", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_attendences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentAttendencesHostel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("biometric_attendence", models.IntegerField(default=0)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "attendence_type_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("remark", models.CharField(max_length=200)),
                ("biometric_device_data", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_attendences_hostel",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentAttendencesTransport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_id", models.IntegerField()),
                ("student_id", models.IntegerField()),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("biometric_attendence", models.IntegerField(default=0)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "attendence_type_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("remark", models.CharField(max_length=200)),
                ("biometric_device_data", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_attendences_transport",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentBehaviour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("point", models.IntegerField()),
                ("description", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_behaviour",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentDoc",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("doc", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "student_doc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentEditFields",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_edit_fields",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentFees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "feemaster_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("amount", models.FloatField(blank=True, null=True)),
                ("amount_discount", models.FloatField()),
                ("amount_fine", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("payment_mode", models.CharField(max_length=50)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_fees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentFeesDeposite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_fees_master_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "fee_groups_feetype_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "student_transport_fee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("amount_detail", models.TextField(blank=True, null=True)),
                ("file", models.TextField(blank=True, null=True)),
                ("is_active", models.CharField(default="no", max_length=10)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_fees_deposite",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentFeesDiscounts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "fees_discount_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="assigned", max_length=20, null=True
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.CharField(default="no", max_length=10)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_fees_discounts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentFeesMaster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_system", models.IntegerField(default=0)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "fee_session_group_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("amount", models.FloatField(blank=True, default="0.00", null=True)),
                ("is_active", models.CharField(default="no", max_length=10)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_fees_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentFeesProcessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gateway_ins_id", models.IntegerField(db_index=True)),
                ("fee_category", models.CharField(max_length=255)),
                (
                    "student_fees_master_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "fee_groups_feetype_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "student_transport_fee_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("amount_detail", models.TextField(blank=True, null=True)),
                ("is_active", models.CharField(default="no", max_length=10)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_fees_processing",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentIncidentComments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_incident_id", models.IntegerField(db_index=True)),
                ("comment", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("staff_id", models.IntegerField()),
                ("student_id", models.IntegerField()),
                ("created_date", models.DateTimeField()),
            ],
            options={
                "db_table": "student_incident_comments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentIncidents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.IntegerField()),
                ("student_id", models.IntegerField(db_index=True)),
                ("incident_id", models.IntegerField(db_index=True)),
                ("assign_by", models.IntegerField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_incidents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentQuizStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("guest_id", models.TextField(blank=True, null=True)),
                (
                    "course_quiz_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("total_question", models.IntegerField(blank=True, null=True)),
                ("correct_answer", models.IntegerField(blank=True, null=True)),
                ("wrong_answer", models.IntegerField(blank=True, null=True)),
                ("not_answer", models.IntegerField(blank=True, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_quiz_status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("parent_id", models.IntegerField()),
                (
                    "admission_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("roll_no", models.BigIntegerField(blank=True, null=True)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("firstname", models.CharField(blank=True, max_length=100, null=True)),
                ("middlename", models.CharField(blank=True, max_length=255, null=True)),
                ("lastname", models.CharField(blank=True, max_length=100, null=True)),
                ("rte", models.CharField(blank=True, max_length=20, null=True)),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
                ("mobileno", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=100, null=True)),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                ("cast", models.CharField(blank=True, max_length=50, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                ("current_address", models.TextField(blank=True, null=True)),
                ("permanent_address", models.TextField(blank=True, null=True)),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("school_house_id", models.IntegerField(blank=True, null=True)),
                ("blood_group", models.CharField(max_length=200)),
                ("hostel_room_id", models.IntegerField(blank=True, null=True)),
                ("room_bed_id", models.IntegerField(blank=True, null=True)),
                ("adhar_no", models.CharField(blank=True, max_length=100, null=True)),
                ("samagra_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                ("ifsc_code", models.CharField(blank=True, max_length=100, null=True)),
                ("guardian_is", models.CharField(max_length=100)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian_relation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("guardian_occupation", models.CharField(max_length=150)),
                ("guardian_address", models.TextField(blank=True, null=True)),
                (
                    "guardian_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_pic", models.CharField(max_length=200)),
                ("mother_pic", models.CharField(max_length=200)),
                ("guardian_pic", models.CharField(max_length=200)),
                (
                    "father_aadhar",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mother_aadhar",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="yes", max_length=255, null=True
                    ),
                ),
                ("previous_school", models.TextField(blank=True, null=True)),
                ("height", models.CharField(max_length=100)),
                ("weight", models.CharField(max_length=100)),
                ("measurement_date", models.DateField(blank=True, null=True)),
                ("dis_reason", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("dis_note", models.TextField()),
                ("app_key", models.TextField(blank=True, null=True)),
                ("parent_app_key", models.TextField(blank=True, null=True)),
                ("disable_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
                ("face_auth", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "students",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "student_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("class_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "section_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("subject_group_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, null=True)),
                ("batch_id", models.IntegerField(blank=True, null=True)),
                ("batch_period_id", models.IntegerField(blank=True, null=True)),
                (
                    "program_period_course_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "hostel_room_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "vehroute_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "route_pickup_point_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("transport_fees", models.FloatField(default="0.00")),
                ("fees_discount", models.FloatField(default="0.00")),
                ("is_leave", models.IntegerField(default=0)),
                (
                    "is_active",
                    models.CharField(
                        blank=True, default="no", max_length=255, null=True
                    ),
                ),
                ("is_alumni", models.IntegerField()),
                ("default_login", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentSubjectAttendances",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "student_session_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "subject_timetable_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "attendence_type_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_subject_attendances",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentTimeline",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("timeline_date", models.DateField()),
                ("description", models.TextField()),
                ("document", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.CharField(max_length=200)),
                ("created_student_id", models.IntegerField()),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "student_timeline",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StudentTransportFees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transport_feemaster_id", models.IntegerField(db_index=True)),
                ("student_session_id", models.IntegerField(db_index=True)),
                ("route_pickup_point_id", models.IntegerField(db_index=True)),
                ("generated_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_transport_fees",
                "managed": False,
            },
        ),
    ]
