from rest_framework import serializers


class VehiclesSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    vehicle_no = serializers.CharField(max_length=20, allow_null=True, allow_blank=True, required=False)
    vehicle_model = serializers.CharField(max_length=100, required=False, default='None')
    vehicle_base_average = serializers.FloatField(allow_null=True, required=False)
    vehicle_photo = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    manufacture_year = serializers.CharField(max_length=4, allow_null=True, allow_blank=True, required=False)
    registration_number = serializers.CharField(max_length=50)
    chasis_number = serializers.CharField(max_length=100)
    max_seating_capacity = serializers.CharField(max_length=255)
    driver_name = serializers.CharField(max_length=50, allow_null=True, allow_blank=True, required=False)
    driver_licence = serializers.CharField(max_length=50, required=False, default='None')
    driver_contact = serializers.CharField(max_length=20, allow_null=True, allow_blank=True, required=False)
    note = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    created_at = serializers.DateTimeField(read_only=True)
    swap_with = serializers.CharField(max_length=44, allow_null=True, allow_blank=True, required=False)
    swap_till = serializers.DateField(allow_null=True, required=False)
    swap_status = serializers.IntegerField(allow_null=True, required=False)
    swap_history = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    v_name = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    v_color = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    v_group = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    v_api_url = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)


class VehiclesCreateSerializer(serializers.Serializer):
    vehicle_no = serializers.CharField(max_length=20, allow_null=True, allow_blank=True, required=False)
    vehicle_model = serializers.CharField(max_length=100, required=False, default='None')
    vehicle_base_average = serializers.FloatField(allow_null=True, required=False)
    vehicle_photo = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    manufacture_year = serializers.CharField(max_length=4, allow_null=True, allow_blank=True, required=False)
    registration_number = serializers.CharField(max_length=50)
    chasis_number = serializers.CharField(max_length=100)
    max_seating_capacity = serializers.CharField(max_length=255)
    driver_name = serializers.CharField(max_length=50, allow_null=True, allow_blank=True, required=False)
    driver_licence = serializers.CharField(max_length=50, required=False, default='None')
    driver_contact = serializers.CharField(max_length=20, allow_null=True, allow_blank=True, required=False)
    note = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    swap_with = serializers.CharField(max_length=44, allow_null=True, allow_blank=True, required=False)
    swap_till = serializers.DateField(allow_null=True, required=False)
    swap_status = serializers.IntegerField(allow_null=True, required=False)
    swap_history = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    v_name = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    v_color = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    v_group = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    v_api_url = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)


class VehiclesUpdateSerializer(serializers.Serializer):
    vehicle_no = serializers.CharField(max_length=20, allow_null=True, allow_blank=True, required=False)
    vehicle_model = serializers.CharField(max_length=100, required=False)
    vehicle_base_average = serializers.FloatField(allow_null=True, required=False)
    vehicle_photo = serializers.CharField(max_length=255, allow_null=True, allow_blank=True, required=False)
    manufacture_year = serializers.CharField(max_length=4, allow_null=True, allow_blank=True, required=False)
    registration_number = serializers.CharField(max_length=50, required=False)
    chasis_number = serializers.CharField(max_length=100, required=False)
    max_seating_capacity = serializers.CharField(max_length=255, required=False)
    driver_name = serializers.CharField(max_length=50, allow_null=True, allow_blank=True, required=False)
    driver_licence = serializers.CharField(max_length=50, required=False)
    driver_contact = serializers.CharField(max_length=20, allow_null=True, allow_blank=True, required=False)
    note = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    swap_with = serializers.CharField(max_length=44, allow_null=True, allow_blank=True, required=False)
    swap_till = serializers.DateField(allow_null=True, required=False)
    swap_status = serializers.IntegerField(allow_null=True, required=False)
    swap_history = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    v_name = serializers.CharField(max_length=255, required=False)
    v_color = serializers.CharField(max_length=255, required=False)
    v_group = serializers.CharField(max_length=255, required=False)
    v_api_url = serializers.CharField(max_length=255, required=False)
